/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.Configuration;
import de.samply.share.client.model.db.tables.records.ConfigurationRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigurationDao extends DAOImpl<ConfigurationRecord, de.samply.share.client.model.db.tables.pojos.Configuration, String> {

    /**
     * Create a new ConfigurationDao without any configuration
     */
    public ConfigurationDao() {
        super(Configuration.CONFIGURATION, de.samply.share.client.model.db.tables.pojos.Configuration.class);
    }

    /**
     * Create a new ConfigurationDao with an attached configuration
     */
    public ConfigurationDao(org.jooq.Configuration configuration) {
        super(Configuration.CONFIGURATION, de.samply.share.client.model.db.tables.pojos.Configuration.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(de.samply.share.client.model.db.tables.pojos.Configuration object) {
        return object.getName();
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Configuration> fetchByName(String... values) {
        return fetch(Configuration.CONFIGURATION.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.Configuration fetchOneByName(String value) {
        return fetchOne(Configuration.CONFIGURATION.NAME, value);
    }

    /**
     * Fetch records that have <code>setting IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Configuration> fetchBySetting(String... values) {
        return fetch(Configuration.CONFIGURATION.SETTING, values);
    }

    /**
     * Fetch records that have <code>visible IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Configuration> fetchByVisible(Boolean... values) {
        return fetch(Configuration.CONFIGURATION.VISIBLE, values);
    }
}
