/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.enums.ReplyRuleType;
import de.samply.share.client.model.db.tables.InquiryHandlingRule;
import de.samply.share.client.model.db.tables.records.InquiryHandlingRuleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Incoming inquiries may be handled differently, depending on several criteria. 
 * Allow to define an "if" part which has to be handled in the application, 
 * a link to a specific broker (may be null), a link to a certain result type 
 * (may also be null) as well as an action to take (e.g. instantly reply a 
 * number)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryHandlingRuleDao extends DAOImpl<InquiryHandlingRuleRecord, de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule, Integer> {

    /**
     * Create a new InquiryHandlingRuleDao without any configuration
     */
    public InquiryHandlingRuleDao() {
        super(InquiryHandlingRule.INQUIRY_HANDLING_RULE, de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule.class);
    }

    /**
     * Create a new InquiryHandlingRuleDao with an attached configuration
     */
    public InquiryHandlingRuleDao(Configuration configuration) {
        super(InquiryHandlingRule.INQUIRY_HANDLING_RULE, de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule> fetchById(Integer... values) {
        return fetch(InquiryHandlingRule.INQUIRY_HANDLING_RULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule fetchOneById(Integer value) {
        return fetchOne(InquiryHandlingRule.INQUIRY_HANDLING_RULE.ID, value);
    }

    /**
     * Fetch records that have <code>broker_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule> fetchByBrokerId(Integer... values) {
        return fetch(InquiryHandlingRule.INQUIRY_HANDLING_RULE.BROKER_ID, values);
    }

    /**
     * Fetch records that have <code>full_result IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule> fetchByFullResult(Boolean... values) {
        return fetch(InquiryHandlingRule.INQUIRY_HANDLING_RULE.FULL_RESULT, values);
    }

    /**
     * Fetch records that have <code>automatic_reply IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryHandlingRule> fetchByAutomaticReply(ReplyRuleType... values) {
        return fetch(InquiryHandlingRule.INQUIRY_HANDLING_RULE.AUTOMATIC_REPLY, values);
    }
}
