/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.InquiryRequestedEntity;
import de.samply.share.client.model.db.tables.records.InquiryRequestedEntityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryRequestedEntityDao extends DAOImpl<InquiryRequestedEntityRecord, de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity, Record2<Integer, Integer>> {

    /**
     * Create a new InquiryRequestedEntityDao without any configuration
     */
    public InquiryRequestedEntityDao() {
        super(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY, de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity.class);
    }

    /**
     * Create a new InquiryRequestedEntityDao with an attached configuration
     */
    public InquiryRequestedEntityDao(Configuration configuration) {
        super(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY, de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity object) {
        return compositeKeyRecord(object.getInquiryId(), object.getRequestedEntityId());
    }

    /**
     * Fetch records that have <code>inquiry_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity> fetchByInquiryId(Integer... values) {
        return fetch(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.INQUIRY_ID, values);
    }

    /**
     * Fetch records that have <code>requested_entity_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryRequestedEntity> fetchByRequestedEntityId(Integer... values) {
        return fetch(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.REQUESTED_ENTITY_ID, values);
    }
}
