/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.Inquiry;
import de.samply.share.client.model.db.tables.records.InquiryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryDao extends DAOImpl<InquiryRecord, de.samply.share.client.model.db.tables.pojos.Inquiry, Integer> {

    /**
     * Create a new InquiryDao without any configuration
     */
    public InquiryDao() {
        super(Inquiry.INQUIRY, de.samply.share.client.model.db.tables.pojos.Inquiry.class);
    }

    /**
     * Create a new InquiryDao with an attached configuration
     */
    public InquiryDao(Configuration configuration) {
        super(Inquiry.INQUIRY, de.samply.share.client.model.db.tables.pojos.Inquiry.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.Inquiry object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchById(Integer... values) {
        return fetch(Inquiry.INQUIRY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.Inquiry fetchOneById(Integer value) {
        return fetchOne(Inquiry.INQUIRY.ID, value);
    }

    /**
     * Fetch records that have <code>upload_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByUploadId(Integer... values) {
        return fetch(Inquiry.INQUIRY.UPLOAD_ID, values);
    }

    /**
     * Fetch records that have <code>source_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchBySourceId(Integer... values) {
        return fetch(Inquiry.INQUIRY.SOURCE_ID, values);
    }

    /**
     * Fetch records that have <code>label IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByLabel(String... values) {
        return fetch(Inquiry.INQUIRY.LABEL, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByDescription(String... values) {
        return fetch(Inquiry.INQUIRY.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>broker_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByBrokerId(Integer... values) {
        return fetch(Inquiry.INQUIRY.BROKER_ID, values);
    }

    /**
     * Fetch records that have <code>latest_details_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByLatestDetailsId(Integer... values) {
        return fetch(Inquiry.INQUIRY.LATEST_DETAILS_ID, values);
    }

    /**
     * Fetch records that have <code>archived_at IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByArchivedAt(Timestamp... values) {
        return fetch(Inquiry.INQUIRY.ARCHIVED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.Inquiry> fetchByDeletedAt(Timestamp... values) {
        return fetch(Inquiry.INQUIRY.DELETED_AT, values);
    }
}
