/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.InquiryAnswer;
import de.samply.share.client.model.db.tables.records.InquiryAnswerRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryAnswerDao extends DAOImpl<InquiryAnswerRecord, de.samply.share.client.model.db.tables.pojos.InquiryAnswer, Integer> {

    /**
     * Create a new InquiryAnswerDao without any configuration
     */
    public InquiryAnswerDao() {
        super(InquiryAnswer.INQUIRY_ANSWER, de.samply.share.client.model.db.tables.pojos.InquiryAnswer.class);
    }

    /**
     * Create a new InquiryAnswerDao with an attached configuration
     */
    public InquiryAnswerDao(Configuration configuration) {
        super(InquiryAnswer.INQUIRY_ANSWER, de.samply.share.client.model.db.tables.pojos.InquiryAnswer.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.InquiryAnswer object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryAnswer> fetchById(Integer... values) {
        return fetch(InquiryAnswer.INQUIRY_ANSWER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.InquiryAnswer fetchOneById(Integer value) {
        return fetchOne(InquiryAnswer.INQUIRY_ANSWER.ID, value);
    }

    /**
     * Fetch records that have <code>inquiry_details_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryAnswer> fetchByInquiryDetailsId(Integer... values) {
        return fetch(InquiryAnswer.INQUIRY_ANSWER.INQUIRY_DETAILS_ID, values);
    }

    /**
     * Fetch a unique record that has <code>inquiry_details_id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.InquiryAnswer fetchOneByInquiryDetailsId(Integer value) {
        return fetchOne(InquiryAnswer.INQUIRY_ANSWER.INQUIRY_DETAILS_ID, value);
    }

    /**
     * Fetch records that have <code>sent_at IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryAnswer> fetchBySentAt(Timestamp... values) {
        return fetch(InquiryAnswer.INQUIRY_ANSWER.SENT_AT, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryAnswer> fetchByContent(String... values) {
        return fetch(InquiryAnswer.INQUIRY_ANSWER.CONTENT, values);
    }
}
