/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.enums.InquiryStatusType;
import de.samply.share.client.model.db.tables.InquiryDetails;
import de.samply.share.client.model.db.tables.records.InquiryDetailsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryDetailsDao extends DAOImpl<InquiryDetailsRecord, de.samply.share.client.model.db.tables.pojos.InquiryDetails, Integer> {

    /**
     * Create a new InquiryDetailsDao without any configuration
     */
    public InquiryDetailsDao() {
        super(InquiryDetails.INQUIRY_DETAILS, de.samply.share.client.model.db.tables.pojos.InquiryDetails.class);
    }

    /**
     * Create a new InquiryDetailsDao with an attached configuration
     */
    public InquiryDetailsDao(Configuration configuration) {
        super(InquiryDetails.INQUIRY_DETAILS, de.samply.share.client.model.db.tables.pojos.InquiryDetails.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.InquiryDetails object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchById(Integer... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.InquiryDetails fetchOneById(Integer value) {
        return fetchOne(InquiryDetails.INQUIRY_DETAILS.ID, value);
    }

    /**
     * Fetch records that have <code>inquiry_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByInquiryId(Integer... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.INQUIRY_ID, values);
    }

    /**
     * Fetch records that have <code>contact_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByContactId(Integer... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.CONTACT_ID, values);
    }

    /**
     * Fetch records that have <code>revision IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByRevision(Integer... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.REVISION, values);
    }

    /**
     * Fetch records that have <code>received_at IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByReceivedAt(Timestamp... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.RECEIVED_AT, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByStatus(InquiryStatusType... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.STATUS, values);
    }

    /**
     * Fetch records that have <code>criteria_original IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByCriteriaOriginal(String... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.CRITERIA_ORIGINAL, values);
    }

    /**
     * Fetch records that have <code>criteria_modified IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByCriteriaModified(String... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.CRITERIA_MODIFIED, values);
    }

    /**
     * Fetch records that have <code>expose_location IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryDetails> fetchByExposeLocation(String... values) {
        return fetch(InquiryDetails.INQUIRY_DETAILS.EXPOSE_LOCATION, values);
    }
}
