/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.InquiryResult;
import de.samply.share.client.model.db.tables.records.InquiryResultRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResultDao extends DAOImpl<InquiryResultRecord, de.samply.share.client.model.db.tables.pojos.InquiryResult, Integer> {

    /**
     * Create a new InquiryResultDao without any configuration
     */
    public InquiryResultDao() {
        super(InquiryResult.INQUIRY_RESULT, de.samply.share.client.model.db.tables.pojos.InquiryResult.class);
    }

    /**
     * Create a new InquiryResultDao with an attached configuration
     */
    public InquiryResultDao(Configuration configuration) {
        super(InquiryResult.INQUIRY_RESULT, de.samply.share.client.model.db.tables.pojos.InquiryResult.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.InquiryResult object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchById(Integer... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.InquiryResult fetchOneById(Integer value) {
        return fetchOne(InquiryResult.INQUIRY_RESULT.ID, value);
    }

    /**
     * Fetch records that have <code>inquiry_details_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByInquiryDetailsId(Integer... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.INQUIRY_DETAILS_ID, values);
    }

    /**
     * Fetch records that have <code>is_error IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByIsError(Boolean... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.IS_ERROR, values);
    }

    /**
     * Fetch records that have <code>location IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByLocation(String... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.LOCATION, values);
    }

    /**
     * Fetch records that have <code>size IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchBySize(Integer... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.SIZE, values);
    }

    /**
     * Fetch records that have <code>executed_at IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByExecutedAt(Timestamp... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.EXECUTED_AT, values);
    }

    /**
     * Fetch records that have <code>valid_until IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByValidUntil(Timestamp... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.VALID_UNTIL, values);
    }

    /**
     * Fetch records that have <code>statistics_only IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByStatisticsOnly(Boolean... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.STATISTICS_ONLY, values);
    }

    /**
     * Fetch records that have <code>notification_sent IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByNotificationSent(Boolean... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.NOTIFICATION_SENT, values);
    }

    /**
     * Fetch records that have <code>error_code IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.InquiryResult> fetchByErrorCode(String... values) {
        return fetch(InquiryResult.INQUIRY_RESULT.ERROR_CODE, values);
    }
}
