/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.JobSchedule;
import de.samply.share.client.model.db.tables.records.JobScheduleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * For regularly executed tasks, set the cron schedule expression here
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobScheduleDao extends DAOImpl<JobScheduleRecord, de.samply.share.client.model.db.tables.pojos.JobSchedule, Integer> {

    /**
     * Create a new JobScheduleDao without any configuration
     */
    public JobScheduleDao() {
        super(JobSchedule.JOB_SCHEDULE, de.samply.share.client.model.db.tables.pojos.JobSchedule.class);
    }

    /**
     * Create a new JobScheduleDao with an attached configuration
     */
    public JobScheduleDao(Configuration configuration) {
        super(JobSchedule.JOB_SCHEDULE, de.samply.share.client.model.db.tables.pojos.JobSchedule.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.JobSchedule object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.JobSchedule> fetchById(Integer... values) {
        return fetch(JobSchedule.JOB_SCHEDULE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.JobSchedule fetchOneById(Integer value) {
        return fetchOne(JobSchedule.JOB_SCHEDULE.ID, value);
    }

    /**
     * Fetch records that have <code>job_key IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.JobSchedule> fetchByJobKey(String... values) {
        return fetch(JobSchedule.JOB_SCHEDULE.JOB_KEY, values);
    }

    /**
     * Fetch a unique record that has <code>job_key = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.JobSchedule fetchOneByJobKey(String value) {
        return fetchOne(JobSchedule.JOB_SCHEDULE.JOB_KEY, value);
    }

    /**
     * Fetch records that have <code>cron_expression IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.JobSchedule> fetchByCronExpression(String... values) {
        return fetch(JobSchedule.JOB_SCHEDULE.CRON_EXPRESSION, values);
    }

    /**
     * Fetch records that have <code>paused IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.JobSchedule> fetchByPaused(Boolean... values) {
        return fetch(JobSchedule.JOB_SCHEDULE.PAUSED, values);
    }
}
