/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.daos;


import de.samply.share.client.model.db.tables.User;
import de.samply.share.client.model.db.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, de.samply.share.client.model.db.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, de.samply.share.client.model.db.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, de.samply.share.client.model.db.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.samply.share.client.model.db.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>token_id IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByTokenId(Integer... values) {
        return fetch(User.USER.TOKEN_ID, values);
    }

    /**
     * Fetch a unique record that has <code>token_id = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.User fetchOneByTokenId(Integer value) {
        return fetchOne(User.USER.TOKEN_ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public de.samply.share.client.model.db.tables.pojos.User fetchOneByUsername(String value) {
        return fetchOne(User.USER.USERNAME, value);
    }

    /**
     * Fetch records that have <code>password_hash IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByPasswordHash(String... values) {
        return fetch(User.USER.PASSWORD_HASH, values);
    }

    /**
     * Fetch records that have <code>real_name IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByRealName(String... values) {
        return fetch(User.USER.REAL_NAME, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByEmail(String... values) {
        return fetch(User.USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>admin_privilege IN (values)</code>
     */
    public List<de.samply.share.client.model.db.tables.pojos.User> fetchByAdminPrivilege(Boolean... values) {
        return fetch(User.USER.ADMIN_PRIVILEGE, values);
    }
}
