/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables;


import de.samply.share.client.model.db.Keys;
import de.samply.share.client.model.db.Samply;
import de.samply.share.client.model.db.tables.records.InquiryRequestedEntityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryRequestedEntity extends TableImpl<InquiryRequestedEntityRecord> {

    private static final long serialVersionUID = 1034111375;

    /**
     * The reference instance of <code>samply.inquiry_requested_entity</code>
     */
    public static final InquiryRequestedEntity INQUIRY_REQUESTED_ENTITY = new InquiryRequestedEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InquiryRequestedEntityRecord> getRecordType() {
        return InquiryRequestedEntityRecord.class;
    }

    /**
     * The column <code>samply.inquiry_requested_entity.inquiry_id</code>.
     */
    public final TableField<InquiryRequestedEntityRecord, Integer> INQUIRY_ID = createField("inquiry_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.inquiry_requested_entity.requested_entity_id</code>.
     */
    public final TableField<InquiryRequestedEntityRecord, Integer> REQUESTED_ENTITY_ID = createField("requested_entity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>samply.inquiry_requested_entity</code> table reference
     */
    public InquiryRequestedEntity() {
        this("inquiry_requested_entity", null);
    }

    /**
     * Create an aliased <code>samply.inquiry_requested_entity</code> table reference
     */
    public InquiryRequestedEntity(String alias) {
        this(alias, INQUIRY_REQUESTED_ENTITY);
    }

    private InquiryRequestedEntity(String alias, Table<InquiryRequestedEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private InquiryRequestedEntity(String alias, Table<InquiryRequestedEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InquiryRequestedEntityRecord> getPrimaryKey() {
        return Keys.INQUIRY_REQUESTED_ENTITY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InquiryRequestedEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<InquiryRequestedEntityRecord>>asList(Keys.INQUIRY_REQUESTED_ENTITY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InquiryRequestedEntityRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InquiryRequestedEntityRecord, ?>>asList(Keys.INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_INQUIRY_ID_FKEY, Keys.INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_REQUESTED_ENTITY_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRequestedEntity as(String alias) {
        return new InquiryRequestedEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InquiryRequestedEntity rename(String name) {
        return new InquiryRequestedEntity(name, null);
    }
}
