/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables;


import de.samply.share.client.model.db.Keys;
import de.samply.share.client.model.db.Samply;
import de.samply.share.client.model.db.tables.records.InquiryResultStatsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResultStats extends TableImpl<InquiryResultStatsRecord> {

    private static final long serialVersionUID = -1300223808;

    /**
     * The reference instance of <code>samply.inquiry_result_stats</code>
     */
    public static final InquiryResultStats INQUIRY_RESULT_STATS = new InquiryResultStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InquiryResultStatsRecord> getRecordType() {
        return InquiryResultStatsRecord.class;
    }

    /**
     * The column <code>samply.inquiry_result_stats.id</code>.
     */
    public final TableField<InquiryResultStatsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('samply.inquiry_result_stats_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>samply.inquiry_result_stats.inquiry_result_id</code>.
     */
    public final TableField<InquiryResultStatsRecord, Integer> INQUIRY_RESULT_ID = createField("inquiry_result_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>samply.inquiry_result_stats.stats_gender</code>.
     */
    public final TableField<InquiryResultStatsRecord, String> STATS_GENDER = createField("stats_gender", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>samply.inquiry_result_stats.stats_age</code>.
     */
    public final TableField<InquiryResultStatsRecord, String> STATS_AGE = createField("stats_age", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>samply.inquiry_result_stats</code> table reference
     */
    public InquiryResultStats() {
        this("inquiry_result_stats", null);
    }

    /**
     * Create an aliased <code>samply.inquiry_result_stats</code> table reference
     */
    public InquiryResultStats(String alias) {
        this(alias, INQUIRY_RESULT_STATS);
    }

    private InquiryResultStats(String alias, Table<InquiryResultStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private InquiryResultStats(String alias, Table<InquiryResultStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<InquiryResultStatsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INQUIRY_RESULT_STATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InquiryResultStatsRecord> getPrimaryKey() {
        return Keys.INQUIRY_RESULT_STATS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InquiryResultStatsRecord>> getKeys() {
        return Arrays.<UniqueKey<InquiryResultStatsRecord>>asList(Keys.INQUIRY_RESULT_STATS_PKEY, Keys.INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InquiryResultStatsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InquiryResultStatsRecord, ?>>asList(Keys.INQUIRY_RESULT_STATS__INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStats as(String alias) {
        return new InquiryResultStats(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InquiryResultStats rename(String name) {
        return new InquiryResultStats(name, null);
    }
}
