CREATE SCHEMA IF NOT EXISTS samply;
SET search_path TO samply,public;

CREATE TYPE auth_scheme_type AS ENUM (
	'AS_APIKEY',
	'AS_BASIC',
	'AS_NTLM',
	'AS_SPNEGO',
	'AS_KERBEROS',
	'AS_DIGEST'
);

CREATE TYPE inquiry_status_type AS ENUM (
	'IS_NEW',
	'IS_PROCESSING',
	'IS_READY',
	'IS_LDM_ERROR',
	'IS_ABANDONED',
	'IS_ARCHIVED'
);

CREATE TYPE target_type AS ENUM (
	'TT_CENTRALSEARCH',
	'TT_HTTP_PROXY',
	'TT_HTTPS_PROXY',
	'TT_LDM',
	'TT_BROKER'
);

CREATE TYPE reply_rule_type AS ENUM (
	'RR_NO_AUTOMATIC_ACTION',
	'RR_TOTAL_COUNT',
	'RR_DATA'
);

CREATE TYPE entity_type AS ENUM (
	'E_BIOMATERIAL',
	'E_CLINICAL_DATA',
	'E_PATIENT_FOR_STUDY'
);

CREATE TYPE broker_status_type AS ENUM (
	'BS_UNREACHABLE',
	'BS_USER_UNKNOWN',
	'BS_AUTHENTICATION_ERROR',
	'BS_ACTIVATION_PENDING',
	'BS_OK'
);

CREATE TYPE upload_status_type AS ENUM (
	'US_NEW',
	'US_QUERY_POSTED',
	'US_QUERY_READY',
	'US_UPLOADING',
	'US_COMPLETED',
	'US_COMPLETED_WITH_ERRORS',
	'US_LDM_ERROR',
	'US_CENTRAL_MDSDB_ERROR',
	'US_IDMANAGER_ERROR',
	'US_ABANDONED',
	'US_CANCELED'
);

CREATE TYPE event_message_type AS ENUM (
	'E_SYSTEM_STARTUP',
	'E_SYSTEM_SHUTDOWN',
  'E_NEW_INQUIRY_RECEIVED',
  'E_NEW_INQUIRY_CREATED_FOR_UPLOAD',
  'E_COULD_NOT_GET_RESULT',
  'E_RESULT_EMPTY',
  'E_START_EXECUTE_INQUIRY_JOB',
	'E_REPEAT_EXECUTE_INQUIRY_JOB_WITHOUT_UNKNOWN_KEYS',
  'E_INQUIRY_RESULT_AT',
  'E_LDM_ERROR',
  'E_STATISTICS_READY',
  'E_INQUIRY_ARCHIVED',
  'E_BROKER_REPLY_ERROR',
  'E_STATUS_CHECK_ABANDONED',
  'E_ARCHIVE_INQUIRY_AFTER_THRESHOLD',
  'E_ARCHIVE_INQUIRY_RESULT_UNAVAILABLE',
  'E_RESULT_NOT_SET_ABORTING',
  'E_FAILED_JAXB_ERROR',
  'E_REPLY_SENT_TO_BROKER',
  'E_DRYRUN_COMPLETE',
  'E_UPLOAD_COMPLETE',
  'E_DELETE_ANONYMIZED_PATIENTS',
  'E_CENTRALSEARCH_COULD_NOT_CONNECT',
  'E_UPLOADSTATS_UNPARSABLE',
  'E_UPLOAD_SET_TIMESTAMP',
  'E_PATIENT_UPLOAD_RESULT',
  'E_UNAUTHORIZED_ATTEMPT_TO_ACCESS_ADMIN_AREA',
  'E_USER_CREATED',
  'E_USER_DELETED',
  'E_NO_CREDENTIALS_CS',
  'E_NO_PREVIOUS_UPLOADS',
  'E_PREVIOUS_UPLOAD_AT',
  'E_CS_ERROR_LASTUPLOADTIMESTAMP'
);

COMMENT ON SCHEMA samply IS 'schema used for samply share';