/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.enums;


import de.samply.share.client.model.db.Samply;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UploadStatusType implements EnumType {

    US_NEW("US_NEW"),

    US_QUERY_POSTED("US_QUERY_POSTED"),

    US_QUERY_READY("US_QUERY_READY"),

    US_UPLOADING("US_UPLOADING"),

    US_COMPLETED("US_COMPLETED"),

    US_COMPLETED_WITH_ERRORS("US_COMPLETED_WITH_ERRORS"),

    US_LDM_ERROR("US_LDM_ERROR"),

    US_CENTRAL_MDSDB_ERROR("US_CENTRAL_MDSDB_ERROR"),

    US_IDMANAGER_ERROR("US_IDMANAGER_ERROR"),

    US_ABANDONED("US_ABANDONED"),

    US_CANCELED("US_CANCELED");

    private final String literal;

    private UploadStatusType(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Samply.SAMPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "upload_status_type";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
