package de.samply.share.client.model;

/**
 * Timing related configuration items. Used to control intervals in job scheduling.
 */
public enum EnumConfigurationTimings {
  JOB_CHECK_INQUIRY_STATUS_INITIAL_DELAY_SECONDS,
  JOB_CHECK_INQUIRY_STATUS_STATS_RETRY_INTERVAL_SECONDS,
  JOB_CHECK_INQUIRY_STATUS_STATS_RETRY_ATTEMPTS,
  JOB_CHECK_INQUIRY_STATUS_RESULTS_RETRY_INTERVAL_SECONDS,
  JOB_CHECK_INQUIRY_STATUS_RESULTS_RETRY_ATTEMPTS,
  JOB_CHECK_SCHEDULED_INQUIRY_INTERVAL_MINUTES,
  JOB_MOVE_INQUIRIES_TO_ARCHIVE_AFTER_DAYS,
  UPLOAD_RETRY_PATIENT_UPLOAD_ATTEMPTS,
  UPLOAD_RETRY_PATIENT_UPLOAD_INTERVAL
}
