/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db;


import de.samply.share.client.model.db.tables.Broker;
import de.samply.share.client.model.db.tables.Configuration;
import de.samply.share.client.model.db.tables.ConfigurationTimings;
import de.samply.share.client.model.db.tables.Contact;
import de.samply.share.client.model.db.tables.Credentials;
import de.samply.share.client.model.db.tables.Document;
import de.samply.share.client.model.db.tables.EventLog;
import de.samply.share.client.model.db.tables.Inquiry;
import de.samply.share.client.model.db.tables.InquiryAnswer;
import de.samply.share.client.model.db.tables.InquiryDetails;
import de.samply.share.client.model.db.tables.InquiryHandlingRule;
import de.samply.share.client.model.db.tables.InquiryRequestedEntity;
import de.samply.share.client.model.db.tables.InquiryResult;
import de.samply.share.client.model.db.tables.InquiryResultStats;
import de.samply.share.client.model.db.tables.JobSchedule;
import de.samply.share.client.model.db.tables.RequestedEntity;
import de.samply.share.client.model.db.tables.Token;
import de.samply.share.client.model.db.tables.Upload;
import de.samply.share.client.model.db.tables.User;
import de.samply.share.client.model.db.tables.UserNotification;
import de.samply.share.client.model.db.tables.UserSeenInquiry;
import de.samply.share.client.model.db.tables.records.BrokerRecord;
import de.samply.share.client.model.db.tables.records.ConfigurationRecord;
import de.samply.share.client.model.db.tables.records.ConfigurationTimingsRecord;
import de.samply.share.client.model.db.tables.records.ContactRecord;
import de.samply.share.client.model.db.tables.records.CredentialsRecord;
import de.samply.share.client.model.db.tables.records.DocumentRecord;
import de.samply.share.client.model.db.tables.records.EventLogRecord;
import de.samply.share.client.model.db.tables.records.InquiryAnswerRecord;
import de.samply.share.client.model.db.tables.records.InquiryDetailsRecord;
import de.samply.share.client.model.db.tables.records.InquiryHandlingRuleRecord;
import de.samply.share.client.model.db.tables.records.InquiryRecord;
import de.samply.share.client.model.db.tables.records.InquiryRequestedEntityRecord;
import de.samply.share.client.model.db.tables.records.InquiryResultRecord;
import de.samply.share.client.model.db.tables.records.InquiryResultStatsRecord;
import de.samply.share.client.model.db.tables.records.JobScheduleRecord;
import de.samply.share.client.model.db.tables.records.RequestedEntityRecord;
import de.samply.share.client.model.db.tables.records.TokenRecord;
import de.samply.share.client.model.db.tables.records.UploadRecord;
import de.samply.share.client.model.db.tables.records.UserNotificationRecord;
import de.samply.share.client.model.db.tables.records.UserRecord;
import de.samply.share.client.model.db.tables.records.UserSeenInquiryRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>samply</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BrokerRecord, Integer> IDENTITY_BROKER = Identities0.IDENTITY_BROKER;
    public static final Identity<ContactRecord, Integer> IDENTITY_CONTACT = Identities0.IDENTITY_CONTACT;
    public static final Identity<CredentialsRecord, Integer> IDENTITY_CREDENTIALS = Identities0.IDENTITY_CREDENTIALS;
    public static final Identity<DocumentRecord, Integer> IDENTITY_DOCUMENT = Identities0.IDENTITY_DOCUMENT;
    public static final Identity<EventLogRecord, Integer> IDENTITY_EVENT_LOG = Identities0.IDENTITY_EVENT_LOG;
    public static final Identity<InquiryRecord, Integer> IDENTITY_INQUIRY = Identities0.IDENTITY_INQUIRY;
    public static final Identity<InquiryAnswerRecord, Integer> IDENTITY_INQUIRY_ANSWER = Identities0.IDENTITY_INQUIRY_ANSWER;
    public static final Identity<InquiryDetailsRecord, Integer> IDENTITY_INQUIRY_DETAILS = Identities0.IDENTITY_INQUIRY_DETAILS;
    public static final Identity<InquiryHandlingRuleRecord, Integer> IDENTITY_INQUIRY_HANDLING_RULE = Identities0.IDENTITY_INQUIRY_HANDLING_RULE;
    public static final Identity<InquiryResultRecord, Integer> IDENTITY_INQUIRY_RESULT = Identities0.IDENTITY_INQUIRY_RESULT;
    public static final Identity<InquiryResultStatsRecord, Integer> IDENTITY_INQUIRY_RESULT_STATS = Identities0.IDENTITY_INQUIRY_RESULT_STATS;
    public static final Identity<JobScheduleRecord, Integer> IDENTITY_JOB_SCHEDULE = Identities0.IDENTITY_JOB_SCHEDULE;
    public static final Identity<RequestedEntityRecord, Integer> IDENTITY_REQUESTED_ENTITY = Identities0.IDENTITY_REQUESTED_ENTITY;
    public static final Identity<TokenRecord, Integer> IDENTITY_TOKEN = Identities0.IDENTITY_TOKEN;
    public static final Identity<UploadRecord, Integer> IDENTITY_UPLOAD = Identities0.IDENTITY_UPLOAD;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BrokerRecord> BROKER_PKEY = UniqueKeys0.BROKER_PKEY;
    public static final UniqueKey<ConfigurationRecord> CONFIGURATION_PKEY = UniqueKeys0.CONFIGURATION_PKEY;
    public static final UniqueKey<ConfigurationTimingsRecord> CONFIGURATION_TIMINGS_PKEY = UniqueKeys0.CONFIGURATION_TIMINGS_PKEY;
    public static final UniqueKey<ContactRecord> CONTACT_PKEY = UniqueKeys0.CONTACT_PKEY;
    public static final UniqueKey<CredentialsRecord> CREDENTIALS_PKEY = UniqueKeys0.CREDENTIALS_PKEY;
    public static final UniqueKey<DocumentRecord> DOCUMENT_PKEY = UniqueKeys0.DOCUMENT_PKEY;
    public static final UniqueKey<EventLogRecord> EVENT_LOG_PKEY = UniqueKeys0.EVENT_LOG_PKEY;
    public static final UniqueKey<InquiryRecord> INQUIRY_PKEY = UniqueKeys0.INQUIRY_PKEY;
    public static final UniqueKey<InquiryAnswerRecord> INQUIRY_ANSWER_PKEY = UniqueKeys0.INQUIRY_ANSWER_PKEY;
    public static final UniqueKey<InquiryAnswerRecord> INQUIRY_ANSWER_INQUIRY_DETAILS_ID_KEY = UniqueKeys0.INQUIRY_ANSWER_INQUIRY_DETAILS_ID_KEY;
    public static final UniqueKey<InquiryDetailsRecord> INQUIRY_DETAILS_PKEY = UniqueKeys0.INQUIRY_DETAILS_PKEY;
    public static final UniqueKey<InquiryHandlingRuleRecord> INQUIRY_HANDLING_RULE_PKEY = UniqueKeys0.INQUIRY_HANDLING_RULE_PKEY;
    public static final UniqueKey<InquiryRequestedEntityRecord> INQUIRY_REQUESTED_ENTITY_PKEY = UniqueKeys0.INQUIRY_REQUESTED_ENTITY_PKEY;
    public static final UniqueKey<InquiryResultRecord> INQUIRY_RESULT_PKEY = UniqueKeys0.INQUIRY_RESULT_PKEY;
    public static final UniqueKey<InquiryResultStatsRecord> INQUIRY_RESULT_STATS_PKEY = UniqueKeys0.INQUIRY_RESULT_STATS_PKEY;
    public static final UniqueKey<InquiryResultStatsRecord> INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_KEY = UniqueKeys0.INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_KEY;
    public static final UniqueKey<JobScheduleRecord> JOB_SCHEDULE_PKEY = UniqueKeys0.JOB_SCHEDULE_PKEY;
    public static final UniqueKey<JobScheduleRecord> JOB_SCHEDULE_JOB_KEY_KEY = UniqueKeys0.JOB_SCHEDULE_JOB_KEY_KEY;
    public static final UniqueKey<RequestedEntityRecord> REQUESTED_ENTITY_PKEY = UniqueKeys0.REQUESTED_ENTITY_PKEY;
    public static final UniqueKey<RequestedEntityRecord> REQUESTED_ENTITY_NAME_KEY = UniqueKeys0.REQUESTED_ENTITY_NAME_KEY;
    public static final UniqueKey<TokenRecord> TOKEN_PKEY = UniqueKeys0.TOKEN_PKEY;
    public static final UniqueKey<TokenRecord> TOKEN_APIKEY_KEY = UniqueKeys0.TOKEN_APIKEY_KEY;
    public static final UniqueKey<UploadRecord> UPLOAD_PKEY = UniqueKeys0.UPLOAD_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<UserRecord> USER_TOKEN_ID_KEY = UniqueKeys0.USER_TOKEN_ID_KEY;
    public static final UniqueKey<UserRecord> USER_USERNAME_KEY = UniqueKeys0.USER_USERNAME_KEY;
    public static final UniqueKey<UserNotificationRecord> USER_NOTIFICATION_PKEY = UniqueKeys0.USER_NOTIFICATION_PKEY;
    public static final UniqueKey<UserSeenInquiryRecord> USER_SEEN_INQUIRY_PKEY = UniqueKeys0.USER_SEEN_INQUIRY_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BrokerRecord, CredentialsRecord> BROKER__BROKER_CREDENTIALS_ID_FKEY = ForeignKeys0.BROKER__BROKER_CREDENTIALS_ID_FKEY;
    public static final ForeignKey<DocumentRecord, InquiryRecord> DOCUMENT__DOCUMENT_INQUIRY_ID_FKEY = ForeignKeys0.DOCUMENT__DOCUMENT_INQUIRY_ID_FKEY;
    public static final ForeignKey<EventLogRecord, InquiryRecord> EVENT_LOG__EVENT_LOG_INQUIRY_ID_FKEY = ForeignKeys0.EVENT_LOG__EVENT_LOG_INQUIRY_ID_FKEY;
    public static final ForeignKey<EventLogRecord, UploadRecord> EVENT_LOG__EVENT_LOG_UPLOAD_ID_FKEY = ForeignKeys0.EVENT_LOG__EVENT_LOG_UPLOAD_ID_FKEY;
    public static final ForeignKey<EventLogRecord, UserRecord> EVENT_LOG__EVENT_LOG_USER_ID_FKEY = ForeignKeys0.EVENT_LOG__EVENT_LOG_USER_ID_FKEY;
    public static final ForeignKey<InquiryRecord, UploadRecord> INQUIRY__INQUIRY_UPLOAD_ID_FKEY = ForeignKeys0.INQUIRY__INQUIRY_UPLOAD_ID_FKEY;
    public static final ForeignKey<InquiryRecord, BrokerRecord> INQUIRY__INQUIRY_BROKER_ID_FKEY = ForeignKeys0.INQUIRY__INQUIRY_BROKER_ID_FKEY;
    public static final ForeignKey<InquiryRecord, InquiryDetailsRecord> INQUIRY__INQUIRY_LATEST_DETAILS_ID_FKEY = ForeignKeys0.INQUIRY__INQUIRY_LATEST_DETAILS_ID_FKEY;
    public static final ForeignKey<InquiryAnswerRecord, InquiryDetailsRecord> INQUIRY_ANSWER__INQUIRY_ANSWER_INQUIRY_DETAILS_ID_FKEY = ForeignKeys0.INQUIRY_ANSWER__INQUIRY_ANSWER_INQUIRY_DETAILS_ID_FKEY;
    public static final ForeignKey<InquiryDetailsRecord, InquiryRecord> INQUIRY_DETAILS__INQUIRY_DETAILS_INQUIRY_ID_FKEY = ForeignKeys0.INQUIRY_DETAILS__INQUIRY_DETAILS_INQUIRY_ID_FKEY;
    public static final ForeignKey<InquiryDetailsRecord, ContactRecord> INQUIRY_DETAILS__INQUIRY_DETAILS_CONTACT_ID_FKEY = ForeignKeys0.INQUIRY_DETAILS__INQUIRY_DETAILS_CONTACT_ID_FKEY;
    public static final ForeignKey<InquiryHandlingRuleRecord, BrokerRecord> INQUIRY_HANDLING_RULE__INQUIRY_HANDLING_RULE_BROKER_ID_FKEY = ForeignKeys0.INQUIRY_HANDLING_RULE__INQUIRY_HANDLING_RULE_BROKER_ID_FKEY;
    public static final ForeignKey<InquiryRequestedEntityRecord, InquiryRecord> INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_INQUIRY_ID_FKEY = ForeignKeys0.INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_INQUIRY_ID_FKEY;
    public static final ForeignKey<InquiryRequestedEntityRecord, RequestedEntityRecord> INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_REQUESTED_ENTITY_ID_FKEY = ForeignKeys0.INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_REQUESTED_ENTITY_ID_FKEY;
    public static final ForeignKey<InquiryResultRecord, InquiryDetailsRecord> INQUIRY_RESULT__INQUIRY_RESULT_INQUIRY_DETAILS_ID_FKEY = ForeignKeys0.INQUIRY_RESULT__INQUIRY_RESULT_INQUIRY_DETAILS_ID_FKEY;
    public static final ForeignKey<InquiryResultStatsRecord, InquiryResultRecord> INQUIRY_RESULT_STATS__INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_FKEY = ForeignKeys0.INQUIRY_RESULT_STATS__INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_FKEY;
    public static final ForeignKey<UserRecord, TokenRecord> USER__USER_TOKEN_ID_FKEY = ForeignKeys0.USER__USER_TOKEN_ID_FKEY;
    public static final ForeignKey<UserNotificationRecord, UserRecord> USER_NOTIFICATION__USER_NOTIFICATION_USER_ID_FKEY = ForeignKeys0.USER_NOTIFICATION__USER_NOTIFICATION_USER_ID_FKEY;
    public static final ForeignKey<UserNotificationRecord, RequestedEntityRecord> USER_NOTIFICATION__USER_NOTIFICATION_REQUESTED_ENTITY_ID_FKEY = ForeignKeys0.USER_NOTIFICATION__USER_NOTIFICATION_REQUESTED_ENTITY_ID_FKEY;
    public static final ForeignKey<UserSeenInquiryRecord, UserRecord> USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_USER_ID_FKEY = ForeignKeys0.USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_USER_ID_FKEY;
    public static final ForeignKey<UserSeenInquiryRecord, InquiryRecord> USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_INQUIRY_ID_FKEY = ForeignKeys0.USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_INQUIRY_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BrokerRecord, Integer> IDENTITY_BROKER = createIdentity(Broker.BROKER, Broker.BROKER.ID);
        public static Identity<ContactRecord, Integer> IDENTITY_CONTACT = createIdentity(Contact.CONTACT, Contact.CONTACT.ID);
        public static Identity<CredentialsRecord, Integer> IDENTITY_CREDENTIALS = createIdentity(Credentials.CREDENTIALS, Credentials.CREDENTIALS.ID);
        public static Identity<DocumentRecord, Integer> IDENTITY_DOCUMENT = createIdentity(Document.DOCUMENT, Document.DOCUMENT.ID);
        public static Identity<EventLogRecord, Integer> IDENTITY_EVENT_LOG = createIdentity(EventLog.EVENT_LOG, EventLog.EVENT_LOG.ID);
        public static Identity<InquiryRecord, Integer> IDENTITY_INQUIRY = createIdentity(Inquiry.INQUIRY, Inquiry.INQUIRY.ID);
        public static Identity<InquiryAnswerRecord, Integer> IDENTITY_INQUIRY_ANSWER = createIdentity(InquiryAnswer.INQUIRY_ANSWER, InquiryAnswer.INQUIRY_ANSWER.ID);
        public static Identity<InquiryDetailsRecord, Integer> IDENTITY_INQUIRY_DETAILS = createIdentity(InquiryDetails.INQUIRY_DETAILS, InquiryDetails.INQUIRY_DETAILS.ID);
        public static Identity<InquiryHandlingRuleRecord, Integer> IDENTITY_INQUIRY_HANDLING_RULE = createIdentity(InquiryHandlingRule.INQUIRY_HANDLING_RULE, InquiryHandlingRule.INQUIRY_HANDLING_RULE.ID);
        public static Identity<InquiryResultRecord, Integer> IDENTITY_INQUIRY_RESULT = createIdentity(InquiryResult.INQUIRY_RESULT, InquiryResult.INQUIRY_RESULT.ID);
        public static Identity<InquiryResultStatsRecord, Integer> IDENTITY_INQUIRY_RESULT_STATS = createIdentity(InquiryResultStats.INQUIRY_RESULT_STATS, InquiryResultStats.INQUIRY_RESULT_STATS.ID);
        public static Identity<JobScheduleRecord, Integer> IDENTITY_JOB_SCHEDULE = createIdentity(JobSchedule.JOB_SCHEDULE, JobSchedule.JOB_SCHEDULE.ID);
        public static Identity<RequestedEntityRecord, Integer> IDENTITY_REQUESTED_ENTITY = createIdentity(RequestedEntity.REQUESTED_ENTITY, RequestedEntity.REQUESTED_ENTITY.ID);
        public static Identity<TokenRecord, Integer> IDENTITY_TOKEN = createIdentity(Token.TOKEN, Token.TOKEN.ID);
        public static Identity<UploadRecord, Integer> IDENTITY_UPLOAD = createIdentity(Upload.UPLOAD, Upload.UPLOAD.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BrokerRecord> BROKER_PKEY = createUniqueKey(Broker.BROKER, "broker_pkey", Broker.BROKER.ID);
        public static final UniqueKey<ConfigurationRecord> CONFIGURATION_PKEY = createUniqueKey(Configuration.CONFIGURATION, "configuration_pkey", Configuration.CONFIGURATION.NAME);
        public static final UniqueKey<ConfigurationTimingsRecord> CONFIGURATION_TIMINGS_PKEY = createUniqueKey(ConfigurationTimings.CONFIGURATION_TIMINGS, "configuration_timings_pkey", ConfigurationTimings.CONFIGURATION_TIMINGS.NAME);
        public static final UniqueKey<ContactRecord> CONTACT_PKEY = createUniqueKey(Contact.CONTACT, "contact_pkey", Contact.CONTACT.ID);
        public static final UniqueKey<CredentialsRecord> CREDENTIALS_PKEY = createUniqueKey(Credentials.CREDENTIALS, "credentials_pkey", Credentials.CREDENTIALS.ID);
        public static final UniqueKey<DocumentRecord> DOCUMENT_PKEY = createUniqueKey(Document.DOCUMENT, "document_pkey", Document.DOCUMENT.ID);
        public static final UniqueKey<EventLogRecord> EVENT_LOG_PKEY = createUniqueKey(EventLog.EVENT_LOG, "event_log_pkey", EventLog.EVENT_LOG.ID);
        public static final UniqueKey<InquiryRecord> INQUIRY_PKEY = createUniqueKey(Inquiry.INQUIRY, "inquiry_pkey", Inquiry.INQUIRY.ID);
        public static final UniqueKey<InquiryAnswerRecord> INQUIRY_ANSWER_PKEY = createUniqueKey(InquiryAnswer.INQUIRY_ANSWER, "inquiry_answer_pkey", InquiryAnswer.INQUIRY_ANSWER.ID);
        public static final UniqueKey<InquiryAnswerRecord> INQUIRY_ANSWER_INQUIRY_DETAILS_ID_KEY = createUniqueKey(InquiryAnswer.INQUIRY_ANSWER, "inquiry_answer_inquiry_details_id_key", InquiryAnswer.INQUIRY_ANSWER.INQUIRY_DETAILS_ID);
        public static final UniqueKey<InquiryDetailsRecord> INQUIRY_DETAILS_PKEY = createUniqueKey(InquiryDetails.INQUIRY_DETAILS, "inquiry_details_pkey", InquiryDetails.INQUIRY_DETAILS.ID);
        public static final UniqueKey<InquiryHandlingRuleRecord> INQUIRY_HANDLING_RULE_PKEY = createUniqueKey(InquiryHandlingRule.INQUIRY_HANDLING_RULE, "inquiry_handling_rule_pkey", InquiryHandlingRule.INQUIRY_HANDLING_RULE.ID);
        public static final UniqueKey<InquiryRequestedEntityRecord> INQUIRY_REQUESTED_ENTITY_PKEY = createUniqueKey(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY, "inquiry_requested_entity_pkey", InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.INQUIRY_ID, InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.REQUESTED_ENTITY_ID);
        public static final UniqueKey<InquiryResultRecord> INQUIRY_RESULT_PKEY = createUniqueKey(InquiryResult.INQUIRY_RESULT, "inquiry_result_pkey", InquiryResult.INQUIRY_RESULT.ID);
        public static final UniqueKey<InquiryResultStatsRecord> INQUIRY_RESULT_STATS_PKEY = createUniqueKey(InquiryResultStats.INQUIRY_RESULT_STATS, "inquiry_result_stats_pkey", InquiryResultStats.INQUIRY_RESULT_STATS.ID);
        public static final UniqueKey<InquiryResultStatsRecord> INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_KEY = createUniqueKey(InquiryResultStats.INQUIRY_RESULT_STATS, "inquiry_result_stats_inquiry_result_id_key", InquiryResultStats.INQUIRY_RESULT_STATS.INQUIRY_RESULT_ID);
        public static final UniqueKey<JobScheduleRecord> JOB_SCHEDULE_PKEY = createUniqueKey(JobSchedule.JOB_SCHEDULE, "job_schedule_pkey", JobSchedule.JOB_SCHEDULE.ID);
        public static final UniqueKey<JobScheduleRecord> JOB_SCHEDULE_JOB_KEY_KEY = createUniqueKey(JobSchedule.JOB_SCHEDULE, "job_schedule_job_key_key", JobSchedule.JOB_SCHEDULE.JOB_KEY);
        public static final UniqueKey<RequestedEntityRecord> REQUESTED_ENTITY_PKEY = createUniqueKey(RequestedEntity.REQUESTED_ENTITY, "requested_entity_pkey", RequestedEntity.REQUESTED_ENTITY.ID);
        public static final UniqueKey<RequestedEntityRecord> REQUESTED_ENTITY_NAME_KEY = createUniqueKey(RequestedEntity.REQUESTED_ENTITY, "requested_entity_name_key", RequestedEntity.REQUESTED_ENTITY.NAME);
        public static final UniqueKey<TokenRecord> TOKEN_PKEY = createUniqueKey(Token.TOKEN, "token_pkey", Token.TOKEN.ID);
        public static final UniqueKey<TokenRecord> TOKEN_APIKEY_KEY = createUniqueKey(Token.TOKEN, "token_apikey_key", Token.TOKEN.APIKEY);
        public static final UniqueKey<UploadRecord> UPLOAD_PKEY = createUniqueKey(Upload.UPLOAD, "upload_pkey", Upload.UPLOAD.ID);
        public static final UniqueKey<UserRecord> USER_PKEY = createUniqueKey(User.USER, "user_pkey", User.USER.ID);
        public static final UniqueKey<UserRecord> USER_TOKEN_ID_KEY = createUniqueKey(User.USER, "user_token_id_key", User.USER.TOKEN_ID);
        public static final UniqueKey<UserRecord> USER_USERNAME_KEY = createUniqueKey(User.USER, "user_username_key", User.USER.USERNAME);
        public static final UniqueKey<UserNotificationRecord> USER_NOTIFICATION_PKEY = createUniqueKey(UserNotification.USER_NOTIFICATION, "user_notification_pkey", UserNotification.USER_NOTIFICATION.USER_ID, UserNotification.USER_NOTIFICATION.REQUESTED_ENTITY_ID);
        public static final UniqueKey<UserSeenInquiryRecord> USER_SEEN_INQUIRY_PKEY = createUniqueKey(UserSeenInquiry.USER_SEEN_INQUIRY, "user_seen_inquiry_pkey", UserSeenInquiry.USER_SEEN_INQUIRY.USER_ID, UserSeenInquiry.USER_SEEN_INQUIRY.INQUIRY_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BrokerRecord, CredentialsRecord> BROKER__BROKER_CREDENTIALS_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.CREDENTIALS_PKEY, Broker.BROKER, "broker__broker_credentials_id_fkey", Broker.BROKER.CREDENTIALS_ID);
        public static final ForeignKey<DocumentRecord, InquiryRecord> DOCUMENT__DOCUMENT_INQUIRY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_PKEY, Document.DOCUMENT, "document__document_inquiry_id_fkey", Document.DOCUMENT.INQUIRY_ID);
        public static final ForeignKey<EventLogRecord, InquiryRecord> EVENT_LOG__EVENT_LOG_INQUIRY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_PKEY, EventLog.EVENT_LOG, "event_log__event_log_inquiry_id_fkey", EventLog.EVENT_LOG.INQUIRY_ID);
        public static final ForeignKey<EventLogRecord, UploadRecord> EVENT_LOG__EVENT_LOG_UPLOAD_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.UPLOAD_PKEY, EventLog.EVENT_LOG, "event_log__event_log_upload_id_fkey", EventLog.EVENT_LOG.UPLOAD_ID);
        public static final ForeignKey<EventLogRecord, UserRecord> EVENT_LOG__EVENT_LOG_USER_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.USER_PKEY, EventLog.EVENT_LOG, "event_log__event_log_user_id_fkey", EventLog.EVENT_LOG.USER_ID);
        public static final ForeignKey<InquiryRecord, UploadRecord> INQUIRY__INQUIRY_UPLOAD_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.UPLOAD_PKEY, Inquiry.INQUIRY, "inquiry__inquiry_upload_id_fkey", Inquiry.INQUIRY.UPLOAD_ID);
        public static final ForeignKey<InquiryRecord, BrokerRecord> INQUIRY__INQUIRY_BROKER_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.BROKER_PKEY, Inquiry.INQUIRY, "inquiry__inquiry_broker_id_fkey", Inquiry.INQUIRY.BROKER_ID);
        public static final ForeignKey<InquiryRecord, InquiryDetailsRecord> INQUIRY__INQUIRY_LATEST_DETAILS_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_DETAILS_PKEY, Inquiry.INQUIRY, "inquiry__inquiry_latest_details_id_fkey", Inquiry.INQUIRY.LATEST_DETAILS_ID);
        public static final ForeignKey<InquiryAnswerRecord, InquiryDetailsRecord> INQUIRY_ANSWER__INQUIRY_ANSWER_INQUIRY_DETAILS_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_DETAILS_PKEY, InquiryAnswer.INQUIRY_ANSWER, "inquiry_answer__inquiry_answer_inquiry_details_id_fkey", InquiryAnswer.INQUIRY_ANSWER.INQUIRY_DETAILS_ID);
        public static final ForeignKey<InquiryDetailsRecord, InquiryRecord> INQUIRY_DETAILS__INQUIRY_DETAILS_INQUIRY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_PKEY, InquiryDetails.INQUIRY_DETAILS, "inquiry_details__inquiry_details_inquiry_id_fkey", InquiryDetails.INQUIRY_DETAILS.INQUIRY_ID);
        public static final ForeignKey<InquiryDetailsRecord, ContactRecord> INQUIRY_DETAILS__INQUIRY_DETAILS_CONTACT_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.CONTACT_PKEY, InquiryDetails.INQUIRY_DETAILS, "inquiry_details__inquiry_details_contact_id_fkey", InquiryDetails.INQUIRY_DETAILS.CONTACT_ID);
        public static final ForeignKey<InquiryHandlingRuleRecord, BrokerRecord> INQUIRY_HANDLING_RULE__INQUIRY_HANDLING_RULE_BROKER_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.BROKER_PKEY, InquiryHandlingRule.INQUIRY_HANDLING_RULE, "inquiry_handling_rule__inquiry_handling_rule_broker_id_fkey", InquiryHandlingRule.INQUIRY_HANDLING_RULE.BROKER_ID);
        public static final ForeignKey<InquiryRequestedEntityRecord, InquiryRecord> INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_INQUIRY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_PKEY, InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY, "inquiry_requested_entity__inquiry_requested_entity_inquiry_id_fkey", InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.INQUIRY_ID);
        public static final ForeignKey<InquiryRequestedEntityRecord, RequestedEntityRecord> INQUIRY_REQUESTED_ENTITY__INQUIRY_REQUESTED_ENTITY_REQUESTED_ENTITY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.REQUESTED_ENTITY_PKEY, InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY, "inquiry_requested_entity__inquiry_requested_entity_requested_entity_id_fkey", InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.REQUESTED_ENTITY_ID);
        public static final ForeignKey<InquiryResultRecord, InquiryDetailsRecord> INQUIRY_RESULT__INQUIRY_RESULT_INQUIRY_DETAILS_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_DETAILS_PKEY, InquiryResult.INQUIRY_RESULT, "inquiry_result__inquiry_result_inquiry_details_id_fkey", InquiryResult.INQUIRY_RESULT.INQUIRY_DETAILS_ID);
        public static final ForeignKey<InquiryResultStatsRecord, InquiryResultRecord> INQUIRY_RESULT_STATS__INQUIRY_RESULT_STATS_INQUIRY_RESULT_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_RESULT_PKEY, InquiryResultStats.INQUIRY_RESULT_STATS, "inquiry_result_stats__inquiry_result_stats_inquiry_result_id_fkey", InquiryResultStats.INQUIRY_RESULT_STATS.INQUIRY_RESULT_ID);
        public static final ForeignKey<UserRecord, TokenRecord> USER__USER_TOKEN_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.TOKEN_PKEY, User.USER, "user__user_token_id_fkey", User.USER.TOKEN_ID);
        public static final ForeignKey<UserNotificationRecord, UserRecord> USER_NOTIFICATION__USER_NOTIFICATION_USER_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.USER_PKEY, UserNotification.USER_NOTIFICATION, "user_notification__user_notification_user_id_fkey", UserNotification.USER_NOTIFICATION.USER_ID);
        public static final ForeignKey<UserNotificationRecord, RequestedEntityRecord> USER_NOTIFICATION__USER_NOTIFICATION_REQUESTED_ENTITY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.REQUESTED_ENTITY_PKEY, UserNotification.USER_NOTIFICATION, "user_notification__user_notification_requested_entity_id_fkey", UserNotification.USER_NOTIFICATION.REQUESTED_ENTITY_ID);
        public static final ForeignKey<UserSeenInquiryRecord, UserRecord> USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_USER_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.USER_PKEY, UserSeenInquiry.USER_SEEN_INQUIRY, "user_seen_inquiry__user_seen_inquiry_user_id_fkey", UserSeenInquiry.USER_SEEN_INQUIRY.USER_ID);
        public static final ForeignKey<UserSeenInquiryRecord, InquiryRecord> USER_SEEN_INQUIRY__USER_SEEN_INQUIRY_INQUIRY_ID_FKEY = createForeignKey(de.samply.share.client.model.db.Keys.INQUIRY_PKEY, UserSeenInquiry.USER_SEEN_INQUIRY, "user_seen_inquiry__user_seen_inquiry_inquiry_id_fkey", UserSeenInquiry.USER_SEEN_INQUIRY.INQUIRY_ID);
    }
}
