/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in samply
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>samply.broker_id_seq</code>
     */
    public static final Sequence<Long> BROKER_ID_SEQ = new SequenceImpl<Long>("broker_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.contact_id_seq</code>
     */
    public static final Sequence<Long> CONTACT_ID_SEQ = new SequenceImpl<Long>("contact_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.credentials_id_seq</code>
     */
    public static final Sequence<Long> CREDENTIALS_ID_SEQ = new SequenceImpl<Long>("credentials_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.document_id_seq</code>
     */
    public static final Sequence<Long> DOCUMENT_ID_SEQ = new SequenceImpl<Long>("document_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.event_log_id_seq</code>
     */
    public static final Sequence<Long> EVENT_LOG_ID_SEQ = new SequenceImpl<Long>("event_log_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_answer_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_ANSWER_ID_SEQ = new SequenceImpl<Long>("inquiry_answer_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_details_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_DETAILS_ID_SEQ = new SequenceImpl<Long>("inquiry_details_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_handling_rule_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_HANDLING_RULE_ID_SEQ = new SequenceImpl<Long>("inquiry_handling_rule_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_ID_SEQ = new SequenceImpl<Long>("inquiry_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_result_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_RESULT_ID_SEQ = new SequenceImpl<Long>("inquiry_result_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.inquiry_result_stats_id_seq</code>
     */
    public static final Sequence<Long> INQUIRY_RESULT_STATS_ID_SEQ = new SequenceImpl<Long>("inquiry_result_stats_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.job_schedule_id_seq</code>
     */
    public static final Sequence<Long> JOB_SCHEDULE_ID_SEQ = new SequenceImpl<Long>("job_schedule_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.requested_entity_id_seq</code>
     */
    public static final Sequence<Long> REQUESTED_ENTITY_ID_SEQ = new SequenceImpl<Long>("requested_entity_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.token_id_seq</code>
     */
    public static final Sequence<Long> TOKEN_ID_SEQ = new SequenceImpl<Long>("token_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.upload_id_seq</code>
     */
    public static final Sequence<Long> UPLOAD_ID_SEQ = new SequenceImpl<Long>("upload_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>samply.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Samply.SAMPLY, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
