/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db;


import de.samply.share.client.model.db.tables.Broker;
import de.samply.share.client.model.db.tables.Configuration;
import de.samply.share.client.model.db.tables.ConfigurationTimings;
import de.samply.share.client.model.db.tables.Contact;
import de.samply.share.client.model.db.tables.Credentials;
import de.samply.share.client.model.db.tables.Document;
import de.samply.share.client.model.db.tables.EventLog;
import de.samply.share.client.model.db.tables.Inquiry;
import de.samply.share.client.model.db.tables.InquiryAnswer;
import de.samply.share.client.model.db.tables.InquiryDetails;
import de.samply.share.client.model.db.tables.InquiryHandlingRule;
import de.samply.share.client.model.db.tables.InquiryRequestedEntity;
import de.samply.share.client.model.db.tables.InquiryResult;
import de.samply.share.client.model.db.tables.InquiryResultStats;
import de.samply.share.client.model.db.tables.JobSchedule;
import de.samply.share.client.model.db.tables.RequestedEntity;
import de.samply.share.client.model.db.tables.Token;
import de.samply.share.client.model.db.tables.Upload;
import de.samply.share.client.model.db.tables.User;
import de.samply.share.client.model.db.tables.UserNotification;
import de.samply.share.client.model.db.tables.UserSeenInquiry;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in samply
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>samply.broker</code>.
     */
    public static final Broker BROKER = de.samply.share.client.model.db.tables.Broker.BROKER;

    /**
     * The table <code>samply.configuration</code>.
     */
    public static final Configuration CONFIGURATION = de.samply.share.client.model.db.tables.Configuration.CONFIGURATION;

    /**
     * Use an extra table for timing parameters for the sake of simply using integers
     */
    public static final ConfigurationTimings CONFIGURATION_TIMINGS = de.samply.share.client.model.db.tables.ConfigurationTimings.CONFIGURATION_TIMINGS;

    /**
     * The table <code>samply.contact</code>.
     */
    public static final Contact CONTACT = de.samply.share.client.model.db.tables.Contact.CONTACT;

    /**
     * Stored credentials for central search,  searchbrokers, local datamanagement...
     */
    public static final Credentials CREDENTIALS = de.samply.share.client.model.db.tables.Credentials.CREDENTIALS;

    /**
     * Users can upload (modified) export files in order to track what they may have sent to other people
     */
    public static final Document DOCUMENT = de.samply.share.client.model.db.tables.Document.DOCUMENT;

    /**
     * Log certain events that happen during job execution. E.g. Upload was triggered or inquiry was received/executed
     */
    public static final EventLog EVENT_LOG = de.samply.share.client.model.db.tables.EventLog.EVENT_LOG;

    /**
     * The table <code>samply.inquiry</code>.
     */
    public static final Inquiry INQUIRY = de.samply.share.client.model.db.tables.Inquiry.INQUIRY;

    /**
     * The table <code>samply.inquiry_answer</code>.
     */
    public static final InquiryAnswer INQUIRY_ANSWER = de.samply.share.client.model.db.tables.InquiryAnswer.INQUIRY_ANSWER;

    /**
     * The table <code>samply.inquiry_details</code>.
     */
    public static final InquiryDetails INQUIRY_DETAILS = de.samply.share.client.model.db.tables.InquiryDetails.INQUIRY_DETAILS;

    /**
     * Incoming inquiries may be handled differently, depending on several criteria. Allow to define an "if" part which has to be handled in the application, a link to a specific broker (may be null), a link to a certain result type (may also be null) as well as an action to take (e.g. instantly reply a number)
     */
    public static final InquiryHandlingRule INQUIRY_HANDLING_RULE = de.samply.share.client.model.db.tables.InquiryHandlingRule.INQUIRY_HANDLING_RULE;

    /**
     * The table <code>samply.inquiry_requested_entity</code>.
     */
    public static final InquiryRequestedEntity INQUIRY_REQUESTED_ENTITY = de.samply.share.client.model.db.tables.InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY;

    /**
     * The table <code>samply.inquiry_result</code>.
     */
    public static final InquiryResult INQUIRY_RESULT = de.samply.share.client.model.db.tables.InquiryResult.INQUIRY_RESULT;

    /**
     * The table <code>samply.inquiry_result_stats</code>.
     */
    public static final InquiryResultStats INQUIRY_RESULT_STATS = de.samply.share.client.model.db.tables.InquiryResultStats.INQUIRY_RESULT_STATS;

    /**
     * For regularly executed tasks, set the cron schedule expression here
     */
    public static final JobSchedule JOB_SCHEDULE = de.samply.share.client.model.db.tables.JobSchedule.JOB_SCHEDULE;

    /**
     * An inquirer can request different types of entities (biomaterial, clinical data...)
     */
    public static final RequestedEntity REQUESTED_ENTITY = de.samply.share.client.model.db.tables.RequestedEntity.REQUESTED_ENTITY;

    /**
     * The table <code>samply.token</code>.
     */
    public static final Token TOKEN = de.samply.share.client.model.db.tables.Token.TOKEN;

    /**
     * Uploads to central search.
     */
    public static final Upload UPLOAD = de.samply.share.client.model.db.tables.Upload.UPLOAD;

    /**
     * The table <code>samply.user</code>.
     */
    public static final User USER = de.samply.share.client.model.db.tables.User.USER;

    /**
     * Which user shall receive which notifications?
     */
    public static final UserNotification USER_NOTIFICATION = de.samply.share.client.model.db.tables.UserNotification.USER_NOTIFICATION;

    /**
     * The table <code>samply.user_seen_inquiry</code>.
     */
    public static final UserSeenInquiry USER_SEEN_INQUIRY = de.samply.share.client.model.db.tables.UserSeenInquiry.USER_SEEN_INQUIRY;
}
