/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.BrokerStatusType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Broker implements Serializable {

    private static final long serialVersionUID = -959725071;

    private Integer          id;
    private String           address;
    private String           name;
    private Timestamp        lastChecked;
    private Integer          credentialsId;
    private BrokerStatusType status;

    public Broker() {}

    public Broker(Broker value) {
        this.id = value.id;
        this.address = value.address;
        this.name = value.name;
        this.lastChecked = value.lastChecked;
        this.credentialsId = value.credentialsId;
        this.status = value.status;
    }

    public Broker(
        Integer          id,
        String           address,
        String           name,
        Timestamp        lastChecked,
        Integer          credentialsId,
        BrokerStatusType status
    ) {
        this.id = id;
        this.address = address;
        this.name = name;
        this.lastChecked = lastChecked;
        this.credentialsId = credentialsId;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getLastChecked() {
        return this.lastChecked;
    }

    public void setLastChecked(Timestamp lastChecked) {
        this.lastChecked = lastChecked;
    }

    public Integer getCredentialsId() {
        return this.credentialsId;
    }

    public void setCredentialsId(Integer credentialsId) {
        this.credentialsId = credentialsId;
    }

    public BrokerStatusType getStatus() {
        return this.status;
    }

    public void setStatus(BrokerStatusType status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Broker (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(name);
        sb.append(", ").append(lastChecked);
        sb.append(", ").append(credentialsId);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
