/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Configuration implements Serializable {

    private static final long serialVersionUID = 599973995;

    private String  name;
    private String  setting;
    private Boolean visible;

    public Configuration() {}

    public Configuration(Configuration value) {
        this.name = value.name;
        this.setting = value.setting;
        this.visible = value.visible;
    }

    public Configuration(
        String  name,
        String  setting,
        Boolean visible
    ) {
        this.name = name;
        this.setting = setting;
        this.visible = visible;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSetting() {
        return this.setting;
    }

    public void setSetting(String setting) {
        this.setting = setting;
    }

    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Configuration (");

        sb.append(name);
        sb.append(", ").append(setting);
        sb.append(", ").append(visible);

        sb.append(")");
        return sb.toString();
    }
}
