/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Use an extra table for timing parameters for the sake of simply using integers
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigurationTimings implements Serializable {

    private static final long serialVersionUID = 850720291;

    private String  name;
    private Integer setting;
    private Boolean visible;

    public ConfigurationTimings() {}

    public ConfigurationTimings(ConfigurationTimings value) {
        this.name = value.name;
        this.setting = value.setting;
        this.visible = value.visible;
    }

    public ConfigurationTimings(
        String  name,
        Integer setting,
        Boolean visible
    ) {
        this.name = name;
        this.setting = setting;
        this.visible = visible;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSetting() {
        return this.setting;
    }

    public void setSetting(Integer setting) {
        this.setting = setting;
    }

    public Boolean getVisible() {
        return this.visible;
    }

    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConfigurationTimings (");

        sb.append(name);
        sb.append(", ").append(setting);
        sb.append(", ").append(visible);

        sb.append(")");
        return sb.toString();
    }
}
