/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contact implements Serializable {

    private static final long serialVersionUID = 1557948847;

    private Integer id;
    private String  title;
    private String  firstName;
    private String  lastName;
    private String  phone;
    private String  email;
    private String  organizationName;

    public Contact() {}

    public Contact(Contact value) {
        this.id = value.id;
        this.title = value.title;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.phone = value.phone;
        this.email = value.email;
        this.organizationName = value.organizationName;
    }

    public Contact(
        Integer id,
        String  title,
        String  firstName,
        String  lastName,
        String  phone,
        String  email,
        String  organizationName
    ) {
        this.id = id;
        this.title = title;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.organizationName = organizationName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOrganizationName() {
        return this.organizationName;
    }

    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contact (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(organizationName);

        sb.append(")");
        return sb.toString();
    }
}
