/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * Users can upload (modified) export files in order to track what they may 
 * have sent to other people
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Document implements Serializable {

    private static final long serialVersionUID = 1308496881;

    private Integer id;
    private Integer inquiryId;
    private Integer userId;
    private Date    uploadedAt;
    private String  filetype;
    private String  filename;
    private byte[]  data;

    public Document() {}

    public Document(Document value) {
        this.id = value.id;
        this.inquiryId = value.inquiryId;
        this.userId = value.userId;
        this.uploadedAt = value.uploadedAt;
        this.filetype = value.filetype;
        this.filename = value.filename;
        this.data = value.data;
    }

    public Document(
        Integer id,
        Integer inquiryId,
        Integer userId,
        Date    uploadedAt,
        String  filetype,
        String  filename,
        byte[]  data
    ) {
        this.id = id;
        this.inquiryId = inquiryId;
        this.userId = userId;
        this.uploadedAt = uploadedAt;
        this.filetype = filetype;
        this.filename = filename;
        this.data = data;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInquiryId() {
        return this.inquiryId;
    }

    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Date getUploadedAt() {
        return this.uploadedAt;
    }

    public void setUploadedAt(Date uploadedAt) {
        this.uploadedAt = uploadedAt;
    }

    public String getFiletype() {
        return this.filetype;
    }

    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte... data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Document (");

        sb.append(id);
        sb.append(", ").append(inquiryId);
        sb.append(", ").append(userId);
        sb.append(", ").append(uploadedAt);
        sb.append(", ").append(filetype);
        sb.append(", ").append(filename);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
