/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.EventMessageType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Log certain events that happen during job execution. E.g. Upload was triggered 
 * or inquiry was received/executed
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventLog implements Serializable {

    private static final long serialVersionUID = 1551494714;

    private Integer          id;
    private EventMessageType eventType;
    private Integer          inquiryId;
    private Integer          uploadId;
    private Integer          userId;
    private Integer          qualityReportId;
    private Timestamp        eventTime;
    private Boolean          showInGlobal;
    private String           entry;

    public EventLog() {}

    public EventLog(EventLog value) {
        this.id = value.id;
        this.eventType = value.eventType;
        this.inquiryId = value.inquiryId;
        this.uploadId = value.uploadId;
        this.userId = value.userId;
        this.qualityReportId = value.qualityReportId;
        this.eventTime = value.eventTime;
        this.showInGlobal = value.showInGlobal;
        this.entry = value.entry;
    }

    public EventLog(
        Integer          id,
        EventMessageType eventType,
        Integer          inquiryId,
        Integer          uploadId,
        Integer          userId,
        Integer          qualityReportId,
        Timestamp        eventTime,
        Boolean          showInGlobal,
        String           entry
    ) {
        this.id = id;
        this.eventType = eventType;
        this.inquiryId = inquiryId;
        this.uploadId = uploadId;
        this.userId = userId;
        this.qualityReportId = qualityReportId;
        this.eventTime = eventTime;
        this.showInGlobal = showInGlobal;
        this.entry = entry;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public EventMessageType getEventType() {
        return this.eventType;
    }

    public void setEventType(EventMessageType eventType) {
        this.eventType = eventType;
    }

    public Integer getInquiryId() {
        return this.inquiryId;
    }

    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

    public Integer getUploadId() {
        return this.uploadId;
    }

    public void setUploadId(Integer uploadId) {
        this.uploadId = uploadId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getQualityReportId() {
        return this.qualityReportId;
    }

    public void setQualityReportId(Integer qualityReportId) {
        this.qualityReportId = qualityReportId;
    }

    public Timestamp getEventTime() {
        return this.eventTime;
    }

    public void setEventTime(Timestamp eventTime) {
        this.eventTime = eventTime;
    }

    public Boolean getShowInGlobal() {
        return this.showInGlobal;
    }

    public void setShowInGlobal(Boolean showInGlobal) {
        this.showInGlobal = showInGlobal;
    }

    public String getEntry() {
        return this.entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventLog (");

        sb.append(id);
        sb.append(", ").append(eventType);
        sb.append(", ").append(inquiryId);
        sb.append(", ").append(uploadId);
        sb.append(", ").append(userId);
        sb.append(", ").append(qualityReportId);
        sb.append(", ").append(eventTime);
        sb.append(", ").append(showInGlobal);
        sb.append(", ").append(entry);

        sb.append(")");
        return sb.toString();
    }
}
