/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResultStats implements Serializable {

    private static final long serialVersionUID = -1323040908;

    private Integer id;
    private Integer inquiryResultId;
    private String  statsGender;
    private String  statsAge;

    public InquiryResultStats() {}

    public InquiryResultStats(InquiryResultStats value) {
        this.id = value.id;
        this.inquiryResultId = value.inquiryResultId;
        this.statsGender = value.statsGender;
        this.statsAge = value.statsAge;
    }

    public InquiryResultStats(
        Integer id,
        Integer inquiryResultId,
        String  statsGender,
        String  statsAge
    ) {
        this.id = id;
        this.inquiryResultId = inquiryResultId;
        this.statsGender = statsGender;
        this.statsAge = statsAge;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInquiryResultId() {
        return this.inquiryResultId;
    }

    public void setInquiryResultId(Integer inquiryResultId) {
        this.inquiryResultId = inquiryResultId;
    }

    public String getStatsGender() {
        return this.statsGender;
    }

    public void setStatsGender(String statsGender) {
        this.statsGender = statsGender;
    }

    public String getStatsAge() {
        return this.statsAge;
    }

    public void setStatsAge(String statsAge) {
        this.statsAge = statsAge;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquiryResultStats (");

        sb.append(id);
        sb.append(", ").append(inquiryResultId);
        sb.append(", ").append(statsGender);
        sb.append(", ").append(statsAge);

        sb.append(")");
        return sb.toString();
    }
}
