/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResult implements Serializable {

    private static final long serialVersionUID = -148015316;

    private Integer   id;
    private Integer   inquiryDetailsId;
    private Boolean   isError;
    private String    location;
    private Integer   size;
    private Timestamp executedAt;
    private Timestamp validUntil;
    private Boolean   statisticsOnly;
    private Boolean   notificationSent;
    private String    errorCode;

    public InquiryResult() {}

    public InquiryResult(InquiryResult value) {
        this.id = value.id;
        this.inquiryDetailsId = value.inquiryDetailsId;
        this.isError = value.isError;
        this.location = value.location;
        this.size = value.size;
        this.executedAt = value.executedAt;
        this.validUntil = value.validUntil;
        this.statisticsOnly = value.statisticsOnly;
        this.notificationSent = value.notificationSent;
        this.errorCode = value.errorCode;
    }

    public InquiryResult(
        Integer   id,
        Integer   inquiryDetailsId,
        Boolean   isError,
        String    location,
        Integer   size,
        Timestamp executedAt,
        Timestamp validUntil,
        Boolean   statisticsOnly,
        Boolean   notificationSent,
        String    errorCode
    ) {
        this.id = id;
        this.inquiryDetailsId = inquiryDetailsId;
        this.isError = isError;
        this.location = location;
        this.size = size;
        this.executedAt = executedAt;
        this.validUntil = validUntil;
        this.statisticsOnly = statisticsOnly;
        this.notificationSent = notificationSent;
        this.errorCode = errorCode;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInquiryDetailsId() {
        return this.inquiryDetailsId;
    }

    public void setInquiryDetailsId(Integer inquiryDetailsId) {
        this.inquiryDetailsId = inquiryDetailsId;
    }

    public Boolean getIsError() {
        return this.isError;
    }

    public void setIsError(Boolean isError) {
        this.isError = isError;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public Integer getSize() {
        return this.size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public Timestamp getExecutedAt() {
        return this.executedAt;
    }

    public void setExecutedAt(Timestamp executedAt) {
        this.executedAt = executedAt;
    }

    public Timestamp getValidUntil() {
        return this.validUntil;
    }

    public void setValidUntil(Timestamp validUntil) {
        this.validUntil = validUntil;
    }

    public Boolean getStatisticsOnly() {
        return this.statisticsOnly;
    }

    public void setStatisticsOnly(Boolean statisticsOnly) {
        this.statisticsOnly = statisticsOnly;
    }

    public Boolean getNotificationSent() {
        return this.notificationSent;
    }

    public void setNotificationSent(Boolean notificationSent) {
        this.notificationSent = notificationSent;
    }

    public String getErrorCode() {
        return this.errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquiryResult (");

        sb.append(id);
        sb.append(", ").append(inquiryDetailsId);
        sb.append(", ").append(isError);
        sb.append(", ").append(location);
        sb.append(", ").append(size);
        sb.append(", ").append(executedAt);
        sb.append(", ").append(validUntil);
        sb.append(", ").append(statisticsOnly);
        sb.append(", ").append(notificationSent);
        sb.append(", ").append(errorCode);

        sb.append(")");
        return sb.toString();
    }
}
