/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.InquiryStatusType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryDetails implements Serializable {

    private static final long serialVersionUID = -203405321;

    private Integer           id;
    private Integer           inquiryId;
    private Integer           contactId;
    private Integer           revision;
    private Timestamp         receivedAt;
    private InquiryStatusType status;
    private String            criteriaOriginal;
    private String            criteriaModified;
    private String            exposeLocation;

    public InquiryDetails() {}

    public InquiryDetails(InquiryDetails value) {
        this.id = value.id;
        this.inquiryId = value.inquiryId;
        this.contactId = value.contactId;
        this.revision = value.revision;
        this.receivedAt = value.receivedAt;
        this.status = value.status;
        this.criteriaOriginal = value.criteriaOriginal;
        this.criteriaModified = value.criteriaModified;
        this.exposeLocation = value.exposeLocation;
    }

    public InquiryDetails(
        Integer           id,
        Integer           inquiryId,
        Integer           contactId,
        Integer           revision,
        Timestamp         receivedAt,
        InquiryStatusType status,
        String            criteriaOriginal,
        String            criteriaModified,
        String            exposeLocation
    ) {
        this.id = id;
        this.inquiryId = inquiryId;
        this.contactId = contactId;
        this.revision = revision;
        this.receivedAt = receivedAt;
        this.status = status;
        this.criteriaOriginal = criteriaOriginal;
        this.criteriaModified = criteriaModified;
        this.exposeLocation = exposeLocation;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInquiryId() {
        return this.inquiryId;
    }

    public void setInquiryId(Integer inquiryId) {
        this.inquiryId = inquiryId;
    }

    public Integer getContactId() {
        return this.contactId;
    }

    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    public Integer getRevision() {
        return this.revision;
    }

    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    public Timestamp getReceivedAt() {
        return this.receivedAt;
    }

    public void setReceivedAt(Timestamp receivedAt) {
        this.receivedAt = receivedAt;
    }

    public InquiryStatusType getStatus() {
        return this.status;
    }

    public void setStatus(InquiryStatusType status) {
        this.status = status;
    }

    public String getCriteriaOriginal() {
        return this.criteriaOriginal;
    }

    public void setCriteriaOriginal(String criteriaOriginal) {
        this.criteriaOriginal = criteriaOriginal;
    }

    public String getCriteriaModified() {
        return this.criteriaModified;
    }

    public void setCriteriaModified(String criteriaModified) {
        this.criteriaModified = criteriaModified;
    }

    public String getExposeLocation() {
        return this.exposeLocation;
    }

    public void setExposeLocation(String exposeLocation) {
        this.exposeLocation = exposeLocation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquiryDetails (");

        sb.append(id);
        sb.append(", ").append(inquiryId);
        sb.append(", ").append(contactId);
        sb.append(", ").append(revision);
        sb.append(", ").append(receivedAt);
        sb.append(", ").append(status);
        sb.append(", ").append(criteriaOriginal);
        sb.append(", ").append(criteriaModified);
        sb.append(", ").append(exposeLocation);

        sb.append(")");
        return sb.toString();
    }
}
