/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.ReplyRuleType;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Incoming inquiries may be handled differently, depending on several criteria. 
 * Allow to define an "if" part which has to be handled in the application, 
 * a link to a specific broker (may be null), a link to a certain result type 
 * (may also be null) as well as an action to take (e.g. instantly reply a 
 * number)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryHandlingRule implements Serializable {

    private static final long serialVersionUID = 2034884924;

    private Integer       id;
    private Integer       brokerId;
    private Boolean       fullResult;
    private ReplyRuleType automaticReply;

    public InquiryHandlingRule() {}

    public InquiryHandlingRule(InquiryHandlingRule value) {
        this.id = value.id;
        this.brokerId = value.brokerId;
        this.fullResult = value.fullResult;
        this.automaticReply = value.automaticReply;
    }

    public InquiryHandlingRule(
        Integer       id,
        Integer       brokerId,
        Boolean       fullResult,
        ReplyRuleType automaticReply
    ) {
        this.id = id;
        this.brokerId = brokerId;
        this.fullResult = fullResult;
        this.automaticReply = automaticReply;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getBrokerId() {
        return this.brokerId;
    }

    public void setBrokerId(Integer brokerId) {
        this.brokerId = brokerId;
    }

    public Boolean getFullResult() {
        return this.fullResult;
    }

    public void setFullResult(Boolean fullResult) {
        this.fullResult = fullResult;
    }

    public ReplyRuleType getAutomaticReply() {
        return this.automaticReply;
    }

    public void setAutomaticReply(ReplyRuleType automaticReply) {
        this.automaticReply = automaticReply;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquiryHandlingRule (");

        sb.append(id);
        sb.append(", ").append(brokerId);
        sb.append(", ").append(fullResult);
        sb.append(", ").append(automaticReply);

        sb.append(")");
        return sb.toString();
    }
}
