/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryAnswer implements Serializable {

    private static final long serialVersionUID = -671019075;

    private Integer   id;
    private Integer   inquiryDetailsId;
    private Timestamp sentAt;
    private String    content;

    public InquiryAnswer() {}

    public InquiryAnswer(InquiryAnswer value) {
        this.id = value.id;
        this.inquiryDetailsId = value.inquiryDetailsId;
        this.sentAt = value.sentAt;
        this.content = value.content;
    }

    public InquiryAnswer(
        Integer   id,
        Integer   inquiryDetailsId,
        Timestamp sentAt,
        String    content
    ) {
        this.id = id;
        this.inquiryDetailsId = inquiryDetailsId;
        this.sentAt = sentAt;
        this.content = content;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInquiryDetailsId() {
        return this.inquiryDetailsId;
    }

    public void setInquiryDetailsId(Integer inquiryDetailsId) {
        this.inquiryDetailsId = inquiryDetailsId;
    }

    public Timestamp getSentAt() {
        return this.sentAt;
    }

    public void setSentAt(Timestamp sentAt) {
        this.sentAt = sentAt;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InquiryAnswer (");

        sb.append(id);
        sb.append(", ").append(inquiryDetailsId);
        sb.append(", ").append(sentAt);
        sb.append(", ").append(content);

        sb.append(")");
        return sb.toString();
    }
}
