/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * For regularly executed tasks, set the cron schedule expression here
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobSchedule implements Serializable {

    private static final long serialVersionUID = 1782420311;

    private Integer id;
    private String  jobKey;
    private String  cronExpression;
    private Boolean paused;

    public JobSchedule() {}

    public JobSchedule(JobSchedule value) {
        this.id = value.id;
        this.jobKey = value.jobKey;
        this.cronExpression = value.cronExpression;
        this.paused = value.paused;
    }

    public JobSchedule(
        Integer id,
        String  jobKey,
        String  cronExpression,
        Boolean paused
    ) {
        this.id = id;
        this.jobKey = jobKey;
        this.cronExpression = cronExpression;
        this.paused = paused;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getJobKey() {
        return this.jobKey;
    }

    public void setJobKey(String jobKey) {
        this.jobKey = jobKey;
    }

    public String getCronExpression() {
        return this.cronExpression;
    }

    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public Boolean getPaused() {
        return this.paused;
    }

    public void setPaused(Boolean paused) {
        this.paused = paused;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobSchedule (");

        sb.append(id);
        sb.append(", ").append(jobKey);
        sb.append(", ").append(cronExpression);
        sb.append(", ").append(paused);

        sb.append(")");
        return sb.toString();
    }
}
