/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.EntityType;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * An inquirer can request different types of entities (biomaterial, clinical 
 * data...)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestedEntity implements Serializable {

    private static final long serialVersionUID = 1674636250;

    private Integer    id;
    private EntityType name;

    public RequestedEntity() {}

    public RequestedEntity(RequestedEntity value) {
        this.id = value.id;
        this.name = value.name;
    }

    public RequestedEntity(
        Integer    id,
        EntityType name
    ) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public EntityType getName() {
        return this.name;
    }

    public void setName(EntityType name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequestedEntity (");

        sb.append(id);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
