/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Token implements Serializable {

    private static final long serialVersionUID = 63628168;

    private Integer   id;
    private String    apikey;
    private String    signinToken;
    private Timestamp expiresAt;

    public Token() {}

    public Token(Token value) {
        this.id = value.id;
        this.apikey = value.apikey;
        this.signinToken = value.signinToken;
        this.expiresAt = value.expiresAt;
    }

    public Token(
        Integer   id,
        String    apikey,
        String    signinToken,
        Timestamp expiresAt
    ) {
        this.id = id;
        this.apikey = apikey;
        this.signinToken = signinToken;
        this.expiresAt = expiresAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getApikey() {
        return this.apikey;
    }

    public void setApikey(String apikey) {
        this.apikey = apikey;
    }

    public String getSigninToken() {
        return this.signinToken;
    }

    public void setSigninToken(String signinToken) {
        this.signinToken = signinToken;
    }

    public Timestamp getExpiresAt() {
        return this.expiresAt;
    }

    public void setExpiresAt(Timestamp expiresAt) {
        this.expiresAt = expiresAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Token (");

        sb.append(id);
        sb.append(", ").append(apikey);
        sb.append(", ").append(signinToken);
        sb.append(", ").append(expiresAt);

        sb.append(")");
        return sb.toString();
    }
}
