/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import de.samply.share.client.model.db.enums.UploadStatusType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Uploads to central search.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Upload implements Serializable {

    private static final long serialVersionUID = 1386056391;

    private Integer          id;
    private UploadStatusType status;
    private Timestamp        triggeredAt;
    private String           triggeredBy;
    private Boolean          isDryrun;
    private Boolean          isFullUpload;
    private Boolean          dktkFlagged;
    private Integer          successCount;
    private Integer          failureCount;
    private String           failedPatients;
    private Timestamp        timeToSet;

    public Upload() {}

    public Upload(Upload value) {
        this.id = value.id;
        this.status = value.status;
        this.triggeredAt = value.triggeredAt;
        this.triggeredBy = value.triggeredBy;
        this.isDryrun = value.isDryrun;
        this.isFullUpload = value.isFullUpload;
        this.dktkFlagged = value.dktkFlagged;
        this.successCount = value.successCount;
        this.failureCount = value.failureCount;
        this.failedPatients = value.failedPatients;
        this.timeToSet = value.timeToSet;
    }

    public Upload(
        Integer          id,
        UploadStatusType status,
        Timestamp        triggeredAt,
        String           triggeredBy,
        Boolean          isDryrun,
        Boolean          isFullUpload,
        Boolean          dktkFlagged,
        Integer          successCount,
        Integer          failureCount,
        String           failedPatients,
        Timestamp        timeToSet
    ) {
        this.id = id;
        this.status = status;
        this.triggeredAt = triggeredAt;
        this.triggeredBy = triggeredBy;
        this.isDryrun = isDryrun;
        this.isFullUpload = isFullUpload;
        this.dktkFlagged = dktkFlagged;
        this.successCount = successCount;
        this.failureCount = failureCount;
        this.failedPatients = failedPatients;
        this.timeToSet = timeToSet;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public UploadStatusType getStatus() {
        return this.status;
    }

    public void setStatus(UploadStatusType status) {
        this.status = status;
    }

    public Timestamp getTriggeredAt() {
        return this.triggeredAt;
    }

    public void setTriggeredAt(Timestamp triggeredAt) {
        this.triggeredAt = triggeredAt;
    }

    public String getTriggeredBy() {
        return this.triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    public Boolean getIsDryrun() {
        return this.isDryrun;
    }

    public void setIsDryrun(Boolean isDryrun) {
        this.isDryrun = isDryrun;
    }

    public Boolean getIsFullUpload() {
        return this.isFullUpload;
    }

    public void setIsFullUpload(Boolean isFullUpload) {
        this.isFullUpload = isFullUpload;
    }

    public Boolean getDktkFlagged() {
        return this.dktkFlagged;
    }

    public void setDktkFlagged(Boolean dktkFlagged) {
        this.dktkFlagged = dktkFlagged;
    }

    public Integer getSuccessCount() {
        return this.successCount;
    }

    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

    public Integer getFailureCount() {
        return this.failureCount;
    }

    public void setFailureCount(Integer failureCount) {
        this.failureCount = failureCount;
    }

    public String getFailedPatients() {
        return this.failedPatients;
    }

    public void setFailedPatients(String failedPatients) {
        this.failedPatients = failedPatients;
    }

    public Timestamp getTimeToSet() {
        return this.timeToSet;
    }

    public void setTimeToSet(Timestamp timeToSet) {
        this.timeToSet = timeToSet;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Upload (");

        sb.append(id);
        sb.append(", ").append(status);
        sb.append(", ").append(triggeredAt);
        sb.append(", ").append(triggeredBy);
        sb.append(", ").append(isDryrun);
        sb.append(", ").append(isFullUpload);
        sb.append(", ").append(dktkFlagged);
        sb.append(", ").append(successCount);
        sb.append(", ").append(failureCount);
        sb.append(", ").append(failedPatients);
        sb.append(", ").append(timeToSet);

        sb.append(")");
        return sb.toString();
    }
}
