/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1340274023;

    private Integer id;
    private Integer tokenId;
    private String  username;
    private String  passwordHash;
    private String  realName;
    private String  email;
    private Boolean adminPrivilege;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.tokenId = value.tokenId;
        this.username = value.username;
        this.passwordHash = value.passwordHash;
        this.realName = value.realName;
        this.email = value.email;
        this.adminPrivilege = value.adminPrivilege;
    }

    public User(
        Integer id,
        Integer tokenId,
        String  username,
        String  passwordHash,
        String  realName,
        String  email,
        Boolean adminPrivilege
    ) {
        this.id = id;
        this.tokenId = tokenId;
        this.username = username;
        this.passwordHash = passwordHash;
        this.realName = realName;
        this.email = email;
        this.adminPrivilege = adminPrivilege;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTokenId() {
        return this.tokenId;
    }

    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getAdminPrivilege() {
        return this.adminPrivilege;
    }

    public void setAdminPrivilege(Boolean adminPrivilege) {
        this.adminPrivilege = adminPrivilege;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(tokenId);
        sb.append(", ").append(username);
        sb.append(", ").append(passwordHash);
        sb.append(", ").append(realName);
        sb.append(", ").append(email);
        sb.append(", ").append(adminPrivilege);

        sb.append(")");
        return sb.toString();
    }
}
