/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Which user shall receive which notifications?
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNotification implements Serializable {

    private static final long serialVersionUID = 589367216;

    private Integer userId;
    private Integer requestedEntityId;

    public UserNotification() {}

    public UserNotification(UserNotification value) {
        this.userId = value.userId;
        this.requestedEntityId = value.requestedEntityId;
    }

    public UserNotification(
        Integer userId,
        Integer requestedEntityId
    ) {
        this.userId = userId;
        this.requestedEntityId = requestedEntityId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRequestedEntityId() {
        return this.requestedEntityId;
    }

    public void setRequestedEntityId(Integer requestedEntityId) {
        this.requestedEntityId = requestedEntityId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserNotification (");

        sb.append(userId);
        sb.append(", ").append(requestedEntityId);

        sb.append(")");
        return sb.toString();
    }
}
