UPDATE samply.configuration_timings SET setting='180' WHERE name='JOB_CHECK_INQUIRY_STATUS_RESULTS_RETRY_ATTEMPTS';
UPDATE samply.configuration_timings SET setting='30' WHERE name='JOB_CHECK_INQUIRY_STATUS_STATS_RETRY_INTERVAL_SECONDS';
UPDATE samply.configuration_timings SET setting='20' WHERE name='JOB_CHECK_INQUIRY_STATUS_STATS_RETRY_ATTEMPTS';