UPDATE samply.configuration SET setting='YEAR' WHERE name='QUALITY_REPORT_SCHEDULER_FORMAT';
DELETE FROM samply.configuration WHERE name='QUALITY_REPORT_SCHEDULER_BY_YEAR';
DELETE FROM samply.configuration WHERE name='QUALITY_REPORT_SCHEDULER_BY_MONTH';
