/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.ConfigurationTimings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Use an extra table for timing parameters for the sake of simply using integers
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigurationTimingsRecord extends UpdatableRecordImpl<ConfigurationTimingsRecord> implements Record3<String, Integer, Boolean> {

    private static final long serialVersionUID = 166523924;

    /**
     * Setter for <code>samply.configuration_timings.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.configuration_timings.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>samply.configuration_timings.setting</code>.
     */
    public void setSetting(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.configuration_timings.setting</code>.
     */
    public Integer getSetting() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.configuration_timings.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.configuration_timings.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ConfigurationTimings.CONFIGURATION_TIMINGS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ConfigurationTimings.CONFIGURATION_TIMINGS.SETTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return ConfigurationTimings.CONFIGURATION_TIMINGS.VISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSetting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationTimingsRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationTimingsRecord value2(Integer value) {
        setSetting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationTimingsRecord value3(Boolean value) {
        setVisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfigurationTimingsRecord values(String value1, Integer value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigurationTimingsRecord
     */
    public ConfigurationTimingsRecord() {
        super(ConfigurationTimings.CONFIGURATION_TIMINGS);
    }

    /**
     * Create a detached, initialised ConfigurationTimingsRecord
     */
    public ConfigurationTimingsRecord(String name, Integer setting, Boolean visible) {
        super(ConfigurationTimings.CONFIGURATION_TIMINGS);

        set(0, name);
        set(1, setting);
        set(2, visible);
    }
}
