/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.Inquiry;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryRecord extends UpdatableRecordImpl<InquiryRecord> implements Record9<Integer, Integer, Integer, String, String, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1872878810;

    /**
     * Setter for <code>samply.inquiry.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry.upload_id</code>.
     */
    public void setUploadId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry.upload_id</code>.
     */
    public Integer getUploadId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>samply.inquiry.label</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>samply.inquiry.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>samply.inquiry.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>samply.inquiry.broker_id</code>.
     */
    public void setBrokerId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>samply.inquiry.broker_id</code>.
     */
    public Integer getBrokerId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>samply.inquiry.latest_details_id</code>.
     */
    public void setLatestDetailsId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>samply.inquiry.latest_details_id</code>.
     */
    public Integer getLatestDetailsId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>samply.inquiry.archived_at</code>. if this inquiry was archived...set the timestamp here. if it is not archived, this shall be null
     */
    public void setArchivedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>samply.inquiry.archived_at</code>. if this inquiry was archived...set the timestamp here. if it is not archived, this shall be null
     */
    public Timestamp getArchivedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>samply.inquiry.deleted_at</code>. allow to mark an inquiry as deleted. set to null if it is not deleted
     */
    public void setDeletedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>samply.inquiry.deleted_at</code>. allow to mark an inquiry as deleted. set to null if it is not deleted
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Inquiry.INQUIRY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Inquiry.INQUIRY.UPLOAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Inquiry.INQUIRY.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Inquiry.INQUIRY.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Inquiry.INQUIRY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Inquiry.INQUIRY.BROKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Inquiry.INQUIRY.LATEST_DETAILS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Inquiry.INQUIRY.ARCHIVED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Inquiry.INQUIRY.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUploadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBrokerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLatestDetailsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getArchivedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value2(Integer value) {
        setUploadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value3(Integer value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value4(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value6(Integer value) {
        setBrokerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value7(Integer value) {
        setLatestDetailsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value8(Timestamp value) {
        setArchivedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord value9(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryRecord
     */
    public InquiryRecord() {
        super(Inquiry.INQUIRY);
    }

    /**
     * Create a detached, initialised InquiryRecord
     */
    public InquiryRecord(Integer id, Integer uploadId, Integer sourceId, String label, String description, Integer brokerId, Integer latestDetailsId, Timestamp archivedAt, Timestamp deletedAt) {
        super(Inquiry.INQUIRY);

        set(0, id);
        set(1, uploadId);
        set(2, sourceId);
        set(3, label);
        set(4, description);
        set(5, brokerId);
        set(6, latestDetailsId);
        set(7, archivedAt);
        set(8, deletedAt);
    }
}
