/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.InquiryResultStats;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResultStatsRecord extends UpdatableRecordImpl<InquiryResultStatsRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -766803690;

    /**
     * Setter for <code>samply.inquiry_result_stats.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_result_stats.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_result_stats.inquiry_result_id</code>.
     */
    public void setInquiryResultId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_result_stats.inquiry_result_id</code>.
     */
    public Integer getInquiryResultId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_result_stats.stats_gender</code>.
     */
    public void setStatsGender(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_result_stats.stats_gender</code>.
     */
    public String getStatsGender() {
        return (String) get(2);
    }

    /**
     * Setter for <code>samply.inquiry_result_stats.stats_age</code>.
     */
    public void setStatsAge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry_result_stats.stats_age</code>.
     */
    public String getStatsAge() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryResultStats.INQUIRY_RESULT_STATS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryResultStats.INQUIRY_RESULT_STATS.INQUIRY_RESULT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return InquiryResultStats.INQUIRY_RESULT_STATS.STATS_GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InquiryResultStats.INQUIRY_RESULT_STATS.STATS_AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInquiryResultId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatsGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatsAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStatsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStatsRecord value2(Integer value) {
        setInquiryResultId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStatsRecord value3(String value) {
        setStatsGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStatsRecord value4(String value) {
        setStatsAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultStatsRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryResultStatsRecord
     */
    public InquiryResultStatsRecord() {
        super(InquiryResultStats.INQUIRY_RESULT_STATS);
    }

    /**
     * Create a detached, initialised InquiryResultStatsRecord
     */
    public InquiryResultStatsRecord(Integer id, Integer inquiryResultId, String statsGender, String statsAge) {
        super(InquiryResultStats.INQUIRY_RESULT_STATS);

        set(0, id);
        set(1, inquiryResultId);
        set(2, statsGender);
        set(3, statsAge);
    }
}
