/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.InquiryRequestedEntity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryRequestedEntityRecord extends UpdatableRecordImpl<InquiryRequestedEntityRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 662459089;

    /**
     * Setter for <code>samply.inquiry_requested_entity.inquiry_id</code>.
     */
    public void setInquiryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_requested_entity.inquiry_id</code>.
     */
    public Integer getInquiryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_requested_entity.requested_entity_id</code>.
     */
    public void setRequestedEntityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_requested_entity.requested_entity_id</code>.
     */
    public Integer getRequestedEntityId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.INQUIRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY.REQUESTED_ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInquiryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRequestedEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRequestedEntityRecord value1(Integer value) {
        setInquiryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRequestedEntityRecord value2(Integer value) {
        setRequestedEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryRequestedEntityRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryRequestedEntityRecord
     */
    public InquiryRequestedEntityRecord() {
        super(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY);
    }

    /**
     * Create a detached, initialised InquiryRequestedEntityRecord
     */
    public InquiryRequestedEntityRecord(Integer inquiryId, Integer requestedEntityId) {
        super(InquiryRequestedEntity.INQUIRY_REQUESTED_ENTITY);

        set(0, inquiryId);
        set(1, requestedEntityId);
    }
}
