/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.InquiryResult;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryResultRecord extends UpdatableRecordImpl<InquiryResultRecord> implements Record10<Integer, Integer, Boolean, String, Integer, Timestamp, Timestamp, Boolean, Boolean, String> {

    private static final long serialVersionUID = 171436271;

    /**
     * Setter for <code>samply.inquiry_result.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_result.inquiry_details_id</code>.
     */
    public void setInquiryDetailsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.inquiry_details_id</code>.
     */
    public Integer getInquiryDetailsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_result.is_error</code>.
     */
    public void setIsError(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.is_error</code>.
     */
    public Boolean getIsError() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>samply.inquiry_result.location</code>. The URL where the result can be found
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.location</code>. The URL where the result can be found
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>samply.inquiry_result.size</code>.
     */
    public void setSize(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.size</code>.
     */
    public Integer getSize() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>samply.inquiry_result.executed_at</code>.
     */
    public void setExecutedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.executed_at</code>.
     */
    public Timestamp getExecutedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>samply.inquiry_result.valid_until</code>.
     */
    public void setValidUntil(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.valid_until</code>.
     */
    public Timestamp getValidUntil() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>samply.inquiry_result.statistics_only</code>.
     */
    public void setStatisticsOnly(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.statistics_only</code>.
     */
    public Boolean getStatisticsOnly() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>samply.inquiry_result.notification_sent</code>. has the user been notified about this inquiry?
     */
    public void setNotificationSent(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.notification_sent</code>. has the user been notified about this inquiry?
     */
    public Boolean getNotificationSent() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>samply.inquiry_result.error_code</code>.
     */
    public void setErrorCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>samply.inquiry_result.error_code</code>.
     */
    public String getErrorCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Boolean, String, Integer, Timestamp, Timestamp, Boolean, Boolean, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Boolean, String, Integer, Timestamp, Timestamp, Boolean, Boolean, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryResult.INQUIRY_RESULT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryResult.INQUIRY_RESULT.INQUIRY_DETAILS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return InquiryResult.INQUIRY_RESULT.IS_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InquiryResult.INQUIRY_RESULT.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return InquiryResult.INQUIRY_RESULT.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return InquiryResult.INQUIRY_RESULT.EXECUTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return InquiryResult.INQUIRY_RESULT.VALID_UNTIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return InquiryResult.INQUIRY_RESULT.STATISTICS_ONLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return InquiryResult.INQUIRY_RESULT.NOTIFICATION_SENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return InquiryResult.INQUIRY_RESULT.ERROR_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInquiryDetailsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getExecutedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getValidUntil();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getStatisticsOnly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getNotificationSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getErrorCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value2(Integer value) {
        setInquiryDetailsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value3(Boolean value) {
        setIsError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value4(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value5(Integer value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value6(Timestamp value) {
        setExecutedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value7(Timestamp value) {
        setValidUntil(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value8(Boolean value) {
        setStatisticsOnly(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value9(Boolean value) {
        setNotificationSent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord value10(String value) {
        setErrorCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryResultRecord values(Integer value1, Integer value2, Boolean value3, String value4, Integer value5, Timestamp value6, Timestamp value7, Boolean value8, Boolean value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryResultRecord
     */
    public InquiryResultRecord() {
        super(InquiryResult.INQUIRY_RESULT);
    }

    /**
     * Create a detached, initialised InquiryResultRecord
     */
    public InquiryResultRecord(Integer id, Integer inquiryDetailsId, Boolean isError, String location, Integer size, Timestamp executedAt, Timestamp validUntil, Boolean statisticsOnly, Boolean notificationSent, String errorCode) {
        super(InquiryResult.INQUIRY_RESULT);

        set(0, id);
        set(1, inquiryDetailsId);
        set(2, isError);
        set(3, location);
        set(4, size);
        set(5, executedAt);
        set(6, validUntil);
        set(7, statisticsOnly);
        set(8, notificationSent);
        set(9, errorCode);
    }
}
