/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.InquiryAnswer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryAnswerRecord extends UpdatableRecordImpl<InquiryAnswerRecord> implements Record4<Integer, Integer, Timestamp, String> {

    private static final long serialVersionUID = 1270381199;

    /**
     * Setter for <code>samply.inquiry_answer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_answer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_answer.inquiry_details_id</code>. which revision of the inquiry was answered?
     */
    public void setInquiryDetailsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_answer.inquiry_details_id</code>. which revision of the inquiry was answered?
     */
    public Integer getInquiryDetailsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_answer.sent_at</code>.
     */
    public void setSentAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_answer.sent_at</code>.
     */
    public Timestamp getSentAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>samply.inquiry_answer.content</code>. What was sent? This may contain different types of data...use json to keep it generic
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry_answer.content</code>. What was sent? This may contain different types of data...use json to keep it generic
     */
    public String getContent() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryAnswer.INQUIRY_ANSWER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryAnswer.INQUIRY_ANSWER.INQUIRY_DETAILS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return InquiryAnswer.INQUIRY_ANSWER.SENT_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InquiryAnswer.INQUIRY_ANSWER.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInquiryDetailsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getSentAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryAnswerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryAnswerRecord value2(Integer value) {
        setInquiryDetailsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryAnswerRecord value3(Timestamp value) {
        setSentAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryAnswerRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryAnswerRecord values(Integer value1, Integer value2, Timestamp value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryAnswerRecord
     */
    public InquiryAnswerRecord() {
        super(InquiryAnswer.INQUIRY_ANSWER);
    }

    /**
     * Create a detached, initialised InquiryAnswerRecord
     */
    public InquiryAnswerRecord(Integer id, Integer inquiryDetailsId, Timestamp sentAt, String content) {
        super(InquiryAnswer.INQUIRY_ANSWER);

        set(0, id);
        set(1, inquiryDetailsId);
        set(2, sentAt);
        set(3, content);
    }
}
