/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.enums.InquiryStatusType;
import de.samply.share.client.model.db.tables.InquiryDetails;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryDetailsRecord extends UpdatableRecordImpl<InquiryDetailsRecord> implements Record9<Integer, Integer, Integer, Integer, Timestamp, InquiryStatusType, String, String, String> {

    private static final long serialVersionUID = -1478148237;

    /**
     * Setter for <code>samply.inquiry_details.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_details.inquiry_id</code>.
     */
    public void setInquiryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.inquiry_id</code>.
     */
    public Integer getInquiryId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_details.contact_id</code>.
     */
    public void setContactId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.contact_id</code>.
     */
    public Integer getContactId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>samply.inquiry_details.revision</code>.
     */
    public void setRevision(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.revision</code>.
     */
    public Integer getRevision() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>samply.inquiry_details.received_at</code>.
     */
    public void setReceivedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.received_at</code>.
     */
    public Timestamp getReceivedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>samply.inquiry_details.status</code>.
     */
    public void setStatus(InquiryStatusType value) {
        set(5, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.status</code>.
     */
    public InquiryStatusType getStatus() {
        return (InquiryStatusType) get(5);
    }

    /**
     * Setter for <code>samply.inquiry_details.criteria_original</code>. the criteria xml snippet as received from source
     */
    public void setCriteriaOriginal(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.criteria_original</code>. the criteria xml snippet as received from source
     */
    public String getCriteriaOriginal() {
        return (String) get(6);
    }

    /**
     * Setter for <code>samply.inquiry_details.criteria_modified</code>. if the original criteria had unknown keys which were removed...keep the modified one as well
     */
    public void setCriteriaModified(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.criteria_modified</code>. if the original criteria had unknown keys which were removed...keep the modified one as well
     */
    public String getCriteriaModified() {
        return (String) get(7);
    }

    /**
     * Setter for <code>samply.inquiry_details.expose_location</code>.
     */
    public void setExposeLocation(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>samply.inquiry_details.expose_location</code>.
     */
    public String getExposeLocation() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Timestamp, InquiryStatusType, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Timestamp, InquiryStatusType, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryDetails.INQUIRY_DETAILS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryDetails.INQUIRY_DETAILS.INQUIRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return InquiryDetails.INQUIRY_DETAILS.CONTACT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return InquiryDetails.INQUIRY_DETAILS.REVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return InquiryDetails.INQUIRY_DETAILS.RECEIVED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<InquiryStatusType> field6() {
        return InquiryDetails.INQUIRY_DETAILS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return InquiryDetails.INQUIRY_DETAILS.CRITERIA_ORIGINAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return InquiryDetails.INQUIRY_DETAILS.CRITERIA_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return InquiryDetails.INQUIRY_DETAILS.EXPOSE_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInquiryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getContactId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRevision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getReceivedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryStatusType value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCriteriaOriginal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCriteriaModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getExposeLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value2(Integer value) {
        setInquiryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value3(Integer value) {
        setContactId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value4(Integer value) {
        setRevision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value5(Timestamp value) {
        setReceivedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value6(InquiryStatusType value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value7(String value) {
        setCriteriaOriginal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value8(String value) {
        setCriteriaModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord value9(String value) {
        setExposeLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryDetailsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, InquiryStatusType value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryDetailsRecord
     */
    public InquiryDetailsRecord() {
        super(InquiryDetails.INQUIRY_DETAILS);
    }

    /**
     * Create a detached, initialised InquiryDetailsRecord
     */
    public InquiryDetailsRecord(Integer id, Integer inquiryId, Integer contactId, Integer revision, Timestamp receivedAt, InquiryStatusType status, String criteriaOriginal, String criteriaModified, String exposeLocation) {
        super(InquiryDetails.INQUIRY_DETAILS);

        set(0, id);
        set(1, inquiryId);
        set(2, contactId);
        set(3, revision);
        set(4, receivedAt);
        set(5, status);
        set(6, criteriaOriginal);
        set(7, criteriaModified);
        set(8, exposeLocation);
    }
}
