/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.enums.ReplyRuleType;
import de.samply.share.client.model.db.tables.InquiryHandlingRule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Incoming inquiries may be handled differently, depending on several criteria. 
 * Allow to define an "if" part which has to be handled in the application, 
 * a link to a specific broker (may be null), a link to a certain result type 
 * (may also be null) as well as an action to take (e.g. instantly reply a 
 * number)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryHandlingRuleRecord extends UpdatableRecordImpl<InquiryHandlingRuleRecord> implements Record4<Integer, Integer, Boolean, ReplyRuleType> {

    private static final long serialVersionUID = -2083059599;

    /**
     * Setter for <code>samply.inquiry_handling_rule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.inquiry_handling_rule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.inquiry_handling_rule.broker_id</code>.
     */
    public void setBrokerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.inquiry_handling_rule.broker_id</code>.
     */
    public Integer getBrokerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>samply.inquiry_handling_rule.full_result</code>. Should the full result be generated here?
     */
    public void setFullResult(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.inquiry_handling_rule.full_result</code>. Should the full result be generated here?
     */
    public Boolean getFullResult() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>samply.inquiry_handling_rule.automatic_reply</code>.
     */
    public void setAutomaticReply(ReplyRuleType value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.inquiry_handling_rule.automatic_reply</code>.
     */
    public ReplyRuleType getAutomaticReply() {
        return (ReplyRuleType) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Boolean, ReplyRuleType> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Boolean, ReplyRuleType> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryHandlingRule.INQUIRY_HANDLING_RULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InquiryHandlingRule.INQUIRY_HANDLING_RULE.BROKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return InquiryHandlingRule.INQUIRY_HANDLING_RULE.FULL_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ReplyRuleType> field4() {
        return InquiryHandlingRule.INQUIRY_HANDLING_RULE.AUTOMATIC_REPLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBrokerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getFullResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReplyRuleType value4() {
        return getAutomaticReply();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHandlingRuleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHandlingRuleRecord value2(Integer value) {
        setBrokerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHandlingRuleRecord value3(Boolean value) {
        setFullResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHandlingRuleRecord value4(ReplyRuleType value) {
        setAutomaticReply(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryHandlingRuleRecord values(Integer value1, Integer value2, Boolean value3, ReplyRuleType value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryHandlingRuleRecord
     */
    public InquiryHandlingRuleRecord() {
        super(InquiryHandlingRule.INQUIRY_HANDLING_RULE);
    }

    /**
     * Create a detached, initialised InquiryHandlingRuleRecord
     */
    public InquiryHandlingRuleRecord(Integer id, Integer brokerId, Boolean fullResult, ReplyRuleType automaticReply) {
        super(InquiryHandlingRule.INQUIRY_HANDLING_RULE);

        set(0, id);
        set(1, brokerId);
        set(2, fullResult);
        set(3, automaticReply);
    }
}
