/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.JobSchedule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * For regularly executed tasks, set the cron schedule expression here
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobScheduleRecord extends UpdatableRecordImpl<JobScheduleRecord> implements Record4<Integer, String, String, Boolean> {

    private static final long serialVersionUID = -485045069;

    /**
     * Setter for <code>samply.job_schedule.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.job_schedule.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.job_schedule.job_key</code>.
     */
    public void setJobKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.job_schedule.job_key</code>.
     */
    public String getJobKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>samply.job_schedule.cron_expression</code>.
     */
    public void setCronExpression(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.job_schedule.cron_expression</code>.
     */
    public String getCronExpression() {
        return (String) get(2);
    }

    /**
     * Setter for <code>samply.job_schedule.paused</code>.
     */
    public void setPaused(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.job_schedule.paused</code>.
     */
    public Boolean getPaused() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobSchedule.JOB_SCHEDULE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobSchedule.JOB_SCHEDULE.JOB_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobSchedule.JOB_SCHEDULE.CRON_EXPRESSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return JobSchedule.JOB_SCHEDULE.PAUSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCronExpression();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getPaused();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobScheduleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobScheduleRecord value2(String value) {
        setJobKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobScheduleRecord value3(String value) {
        setCronExpression(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobScheduleRecord value4(Boolean value) {
        setPaused(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobScheduleRecord values(Integer value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobScheduleRecord
     */
    public JobScheduleRecord() {
        super(JobSchedule.JOB_SCHEDULE);
    }

    /**
     * Create a detached, initialised JobScheduleRecord
     */
    public JobScheduleRecord(Integer id, String jobKey, String cronExpression, Boolean paused) {
        super(JobSchedule.JOB_SCHEDULE);

        set(0, id);
        set(1, jobKey);
        set(2, cronExpression);
        set(3, paused);
    }
}
