/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.Token;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenRecord extends UpdatableRecordImpl<TokenRecord> implements Record4<Integer, String, String, Timestamp> {

    private static final long serialVersionUID = 712714506;

    /**
     * Setter for <code>samply.token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.token.apikey</code>.
     */
    public void setApikey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.token.apikey</code>.
     */
    public String getApikey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>samply.token.signin_token</code>.
     */
    public void setSigninToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>samply.token.signin_token</code>.
     */
    public String getSigninToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>samply.token.expires_at</code>.
     */
    public void setExpiresAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>samply.token.expires_at</code>.
     */
    public Timestamp getExpiresAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Token.TOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Token.TOKEN.APIKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Token.TOKEN.SIGNIN_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Token.TOKEN.EXPIRES_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApikey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSigninToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getExpiresAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenRecord value2(String value) {
        setApikey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenRecord value3(String value) {
        setSigninToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenRecord value4(Timestamp value) {
        setExpiresAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenRecord values(Integer value1, String value2, String value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(Integer id, String apikey, String signinToken, Timestamp expiresAt) {
        super(Token.TOKEN);

        set(0, id);
        set(1, apikey);
        set(2, signinToken);
        set(3, expiresAt);
    }
}
