/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.UserNotification;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Which user shall receive which notifications?
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserNotificationRecord extends UpdatableRecordImpl<UserNotificationRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -456140373;

    /**
     * Setter for <code>samply.user_notification.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.user_notification.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.user_notification.requested_entity_id</code>.
     */
    public void setRequestedEntityId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.user_notification.requested_entity_id</code>.
     */
    public Integer getRequestedEntityId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserNotification.USER_NOTIFICATION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserNotification.USER_NOTIFICATION.REQUESTED_ENTITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRequestedEntityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord value2(Integer value) {
        setRequestedEntityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserNotificationRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserNotificationRecord
     */
    public UserNotificationRecord() {
        super(UserNotification.USER_NOTIFICATION);
    }

    /**
     * Create a detached, initialised UserNotificationRecord
     */
    public UserNotificationRecord(Integer userId, Integer requestedEntityId) {
        super(UserNotification.USER_NOTIFICATION);

        set(0, userId);
        set(1, requestedEntityId);
    }
}
