/*
 * This file is generated by jOOQ.
*/
package de.samply.share.client.model.db.tables.records;


import de.samply.share.client.model.db.tables.UserSeenInquiry;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSeenInquiryRecord extends UpdatableRecordImpl<UserSeenInquiryRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1783277272;

    /**
     * Setter for <code>samply.user_seen_inquiry.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>samply.user_seen_inquiry.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>samply.user_seen_inquiry.inquiry_id</code>.
     */
    public void setInquiryId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>samply.user_seen_inquiry.inquiry_id</code>.
     */
    public Integer getInquiryId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserSeenInquiry.USER_SEEN_INQUIRY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserSeenInquiry.USER_SEEN_INQUIRY.INQUIRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInquiryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSeenInquiryRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSeenInquiryRecord value2(Integer value) {
        setInquiryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSeenInquiryRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSeenInquiryRecord
     */
    public UserSeenInquiryRecord() {
        super(UserSeenInquiry.USER_SEEN_INQUIRY);
    }

    /**
     * Create a detached, initialised UserSeenInquiryRecord
     */
    public UserSeenInquiryRecord(Integer userId, Integer inquiryId) {
        super(UserSeenInquiry.USER_SEEN_INQUIRY);

        set(0, userId);
        set(1, inquiryId);
    }
}
